In [56]:
import pandas as pd

# ЗАГРУЖАЕМ

In [234]:
#Выгружаем все данные
df_user = pd.read_sql(
    """
    SELECT *
    FROM "user_data" 
    """,

    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)
df_post = pd.read_sql(
    """
    SELECT *
    FROM "post_text_df" 
    """,

    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)

df_feed = pd.read_sql(
    """
    SELECT *
    FROM "feed_data" 
    LIMIT 500000
    
    """,

    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)

# EDA + DATASET TRANSFORMATIONS

In [235]:
df_user.head()

   user_id  gender  age country               city  exp_group       os source
0      200       1   34  Russia          Degtyarsk          3  Android    ads
1      201       0   37  Russia             Abakan          0  Android    ads
2      202       1   17  Russia           Smolensk          4  Android    ads
3      203       0   18  Russia             Moscow          1      iOS    ads
4      204       0   36  Russia  Anzhero-Sudzhensk          3  Android    ads

In [236]:
df_user.nunique()

user_id      163205
gender            2
age              76
country          11
city           3915
exp_group         5
os                2
source            2
dtype: int64

In [237]:
for col in ['country', 'exp_group', 'os', 'source']:
    ohe = pd.get_dummies(df_user[col], prefix=col, drop_first=True)
    df_user = pd.concat((df_user.drop(col, axis=1), ohe), axis=1)
    
df_user = df_user.drop('city', axis=1)
df_user

,user_id,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,country_Switzerland,country_Turkey,country_Ukraine,exp_group_1,exp_group_2,exp_group_3,exp_group_4,os_iOS,source_organic
0,200,1,34,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0
1,201,0,37,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,202,1,17,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
3,203,0,18,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0
4,204,0,36,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163200,168548,0,36,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1
163201,168549,0,18,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1
163202,168550,1,41,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1
163203,168551,0,38,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,1
163204,168552,1,16,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1

In [61]:
df_post.head()

   post_id                                               text     topic
0        1  UK economy facing major risks\n\nThe UK manufa...  business
1        2  Aids and climate top Davos agenda\n\nClimate c...  business
2        3  Asian quake hits European shares\n\nShares in ...  business
3        4  India power shares jump on debut\n\nShares in ...  business
4        5  Lacroix label bought by US firm\n\nLuxury good...  business

# NN test (Начало)

In [163]:
### Сделаем эмбеддинги постов с помощью моделей из 10 занятия

from transformers import AutoTokenizer
from transformers import BertModel  # https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertModel
from transformers import RobertaModel  # https://huggingface.co/docs/transformers/model_doc/roberta#transformers.RobertaModel
from transformers import DistilBertModel  # https://huggingface.co/docs/transformers/model_doc/distilbert#transformers.DistilBertModel


def get_model(model_name):
    assert model_name in ['bert', 'roberta', 'distilbert']

    checkpoint_names = {
        'bert': 'bert-base-cased',  # https://huggingface.co/bert-base-cased
        'roberta': 'roberta-base',  # https://huggingface.co/roberta-base
        'distilbert': 'distilbert-base-cased'  # https://huggingface.co/distilbert-base-cased
    }

    model_classes = {
        'bert': BertModel,
        'roberta': RobertaModel,
        'distilbert': DistilBertModel
    }

    return AutoTokenizer.from_pretrained(checkpoint_names[model_name]), model_classes[model_name].from_pretrained(checkpoint_names[model_name])

In [164]:
tokenizer, model = get_model('distilbert')

Some weights of the model checkpoint at distilbert-base-cased were not used when initializing DistilBertModel: ['vocab_projector.bias', 'vocab_projector.weight', 'vocab_layer_norm.weight', 'vocab_transform.weight', 'vocab_transform.bias', 'vocab_layer_norm.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [166]:
### Сделаем датасет для постов

from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from transformers import DataCollatorWithPadding


class PostDataset(Dataset):
    def __init__(self, texts, tokenizer):
        super().__init__()

        self.texts = tokenizer.batch_encode_plus(
            texts,
            add_special_tokens=True,
            return_token_type_ids=False,
            return_tensors='pt',
            truncation=True,
            padding=True
        )
        self.tokenizer = tokenizer

    def __getitem__(self, idx):
        return {'input_ids': self.texts['input_ids'][idx], 'attention_mask': self.texts['attention_mask'][idx]}

    def __len__(self):
        return len(self.texts['input_ids'])
    
    
dataset = PostDataset(df_post['text'].values.tolist(), tokenizer)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

loader = DataLoader(dataset, batch_size=32, collate_fn=data_collator, pin_memory=True, shuffle=False)

b = next(iter(loader))

b

You're using a DistilBertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

{'input_ids': tensor([[  101,  1993,  4190,  ...,     0,     0,     0],
        [  101, 15386,  1116,  ...,  1300,  1107,   102],
        [  101,  3141,   186,  ..., 14099,  8478,   102],
        ...,
        [  101, 16972, 20647,  ...,     0,     0,     0],
        [  101,   137,   188,  ...,     0,     0,     0],
        [  101,   144, 22731,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [167]:
import torch
from tqdm import tqdm


@torch.inference_mode()
def get_embeddings_labels(model, loader):
    model.eval()
    
    total_embeddings = []
    
    for batch in tqdm(loader):
        batch = {key: batch[key].to(device) for key in ['attention_mask', 'input_ids']}

        embeddings = model(**batch)['last_hidden_state'][:, 0, :]

        total_embeddings.append(embeddings.cpu())

    return torch.cat(total_embeddings, dim=0)

In [168]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)
#print(torch.cuda.get_device_name())

model = model.to(device)

cpu

In [169]:
embeddings = get_embeddings_labels(model, loader).numpy()

embeddings

100%|████████████████████████████████████████████████████████████████████████████████| 220/220 [35:43<00:00,  9.74s/it]

array([[ 3.63150805e-01,  4.89374883e-02, -2.64081478e-01, ...,
        -1.41593143e-01,  1.59181543e-02,  9.18847509e-05],
       [ 2.36416280e-01, -1.59501165e-01, -3.27798426e-01, ...,
        -2.89936155e-01,  1.19365126e-01, -1.62371807e-03],
       [ 3.75191540e-01, -1.13943890e-01, -2.40547210e-01, ...,
        -3.38919073e-01,  5.86935952e-02, -2.12656353e-02],
       ...,
       [ 3.40382457e-01,  6.64923489e-02, -1.63184613e-01, ...,
        -8.65627229e-02,  2.03403696e-01,  3.20905857e-02],
       [ 4.32092071e-01,  1.10914111e-02, -1.17306188e-01, ...,
         7.54014552e-02,  1.02739751e-01,  1.52741857e-02],
       [ 3.04277599e-01, -7.62156844e-02, -6.77586421e-02, ...,
        -5.43488227e-02,  2.44383588e-01, -1.41483117e-02]], dtype=float32)

In [171]:
### Пытаемся кластеризовать тексты

from sklearn.decomposition import PCA

centered = embeddings - embeddings.mean()

pca = PCA(n_components=20)
pca_decomp = pca.fit_transform(centered)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=15, random_state=0).fit(pca_decomp)

df_post['TextCluster'] = kmeans.labels_

dists_columns = ['DistanceTo1thCluster',
                 'DistanceTo2thCluster',
                 'DistanceTo3thCluster',
                 'DistanceTo4thCluster',
                 'DistanceTo5thCluster',
                 'DistanceTo6thCluster',
                 'DistanceTo7thCluster',
                 'DistanceTo8thCluster',
                 'DistanceTo9thCluster',
                 'DistanceTo10thCluster',
                 'DistanceTo11thCluster',
                 'DistanceTo12thCluster',
                 'DistanceTo13thCluster',
                 'DistanceTo14thCluster',
                 'DistanceTo15thCluster']

dists_df = pd.DataFrame(
    data=kmeans.transform(pca_decomp),
    columns=dists_columns
)

dists_df.head()

,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster
0,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,1.969380,3.350282,1.552706,2.856973,3.283484,3.328180,3.299252,3.274009,3.226359
1,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,1.947727,2.963042,1.431155,2.653073,3.028255,3.160940,2.774500,3.260491,3.178570
2,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,2.831849,2.970637,1.357996,2.913700,3.102815,3.294351,2.775532,3.399966,3.126604
3,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,3.203395,3.670003,2.122464,3.132410,3.520485,3.669621,3.559877,3.584817,3.369332
4,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,2.673844,2.581019,1.345078,2.419489,2.649331,2.551137,2.418449,2.591954,2.823423

In [172]:
df_post = pd.concat((df_post, dists_df), axis=1)

df_post.head()

,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster
0,1,UK economy facing major risks\n\nThe UK manufa...,business,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,1.969380,3.350282,1.552706,2.856973,3.283484,3.328180,3.299252,3.274009,3.226359
1,2,Aids and climate top Davos agenda\n\nClimate c...,business,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,1.947727,2.963042,1.431155,2.653073,3.028255,3.160940,2.774500,3.260491,3.178570
2,3,Asian quake hits European shares\n\nShares in ...,business,8,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,2.831849,2.970637,1.357996,2.913700,3.102815,3.294351,2.775532,3.399966,3.126604
3,4,India power shares jump on debut\n\nShares in ...,business,8,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,3.203395,3.670003,2.122464,3.132410,3.520485,3.669621,3.559877,3.584817,3.369332
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,2.673844,2.581019,1.345078,2.419489,2.649331,2.551137,2.418449,2.591954,2.823423

# NN test (Конец)

# Новый признак (начало)

In [238]:
res = df_feed.groupby(
    df_feed['post_id']
).agg({'target': 'mean'})
res.head()

           target
post_id
1        0.078125
2        0.107143
3        0.128571
4        0.140625
5        0.116667

In [240]:
res = df_feed[df_feed['target'] == 1]
pos = res.groupby(res['post_id']).agg({'target':'count'})

res = df_feed[df_feed['target'] == 0]
neg = res.groupby(res['post_id']).agg({'target':'count'})

In [175]:
post_test = df_post
post_test.head()

,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster
0,1,UK economy facing major risks\n\nThe UK manufa...,business,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,1.969380,3.350282,1.552706,2.856973,3.283484,3.328180,3.299252,3.274009,3.226359
1,2,Aids and climate top Davos agenda\n\nClimate c...,business,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,1.947727,2.963042,1.431155,2.653073,3.028255,3.160940,2.774500,3.260491,3.178570
2,3,Asian quake hits European shares\n\nShares in ...,business,8,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,2.831849,2.970637,1.357996,2.913700,3.102815,3.294351,2.775532,3.399966,3.126604
3,4,India power shares jump on debut\n\nShares in ...,business,8,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,3.203395,3.670003,2.122464,3.132410,3.520485,3.669621,3.559877,3.584817,3.369332
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,2.673844,2.581019,1.345078,2.419489,2.649331,2.551137,2.418449,2.591954,2.823423

In [176]:
post_test = post_test.merge(pos, on='post_id', how='left').fillna(0)
post_test = post_test.merge(neg, on='post_id', how='left').fillna(0)
post_test

,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,...,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,target_x,target_y
0,1,UK economy facing major risks\n\nThe UK manufa...,business,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,...,3.350282,1.552706,2.856973,3.283484,3.328180,3.299252,3.274009,3.226359,2.0,14.0
1,2,Aids and climate top Davos agenda\n\nClimate c...,business,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,...,2.963042,1.431155,2.653073,3.028255,3.160940,2.774500,3.260491,3.178570,2.0,26.0
2,3,Asian quake hits European shares\n\nShares in ...,business,8,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,...,2.970637,1.357996,2.913700,3.102815,3.294351,2.775532,3.399966,3.126604,6.0,27.0
3,4,India power shares jump on debut\n\nShares in ...,business,8,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,...,3.670003,2.122464,3.132410,3.520485,3.669621,3.559877,3.584817,3.369332,5.0,21.0
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,...,2.581019,1.345078,2.419489,2.649331,2.551137,2.418449,2.591954,2.823423,3.0,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7315,"OK, I would not normally watch a Farrelly brot...",movie,0,0.879528,2.180948,2.797818,2.564929,2.130065,3.268162,...,1.614585,2.793543,2.632243,1.916686,1.534206,2.829822,1.416083,2.974245,8.0,39.0
7019,7316,I give this movie 2 stars purely because of it...,movie,0,0.698967,2.086715,2.490488,2.322584,2.111093,3.286735,...,1.692232,2.873902,2.375822,1.713674,1.606385,3.111119,1.003729,2.832663,1.0,8.0
7020,7317,I cant believe this film was allowed to be mad...,movie,0,1.161841,2.444997,2.193800,2.647159,2.271674,3.361959,...,1.826294,3.061269,2.378414,2.133450,1.821000,3.014389,1.761077,2.676703,1.0,20.0
7021,7318,The version I saw of this film was the Blockbu...,movie,13,1.423654,1.947482,3.242426,2.937189,2.261545,3.346242,...,1.566741,3.147256,3.061242,1.938101,1.043027,3.161317,1.028654,3.388523,2.0,19.0
7022,7319,Piece of subtle art. Maybe a masterpiece. Doub...,movie,7,1.778338,2.169969,2.766120,2.585927,2.400287,3.402753,...,1.207134,3.019366,2.711591,1.801625,1.637934,3.004033,1.672995,3.047235,3.0,25.0

In [177]:
post_test['mean_target'] = (post_test['target_x'] / post_test['target_y'])
mean_like = round(post_test['mean_target'].mean(), 3)
mean_like

0.115

In [178]:
post_test[post_test['mean_target'] >= mean_like]

,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,...,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,target_x,target_y,mean_target
0,1,UK economy facing major risks\n\nThe UK manufa...,business,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,...,1.552706,2.856973,3.283484,3.328180,3.299252,3.274009,3.226359,2.0,14.0,0.142857
2,3,Asian quake hits European shares\n\nShares in ...,business,8,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,...,1.357996,2.913700,3.102815,3.294351,2.775532,3.399966,3.126604,6.0,27.0,0.222222
3,4,India power shares jump on debut\n\nShares in ...,business,8,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,...,2.122464,3.132410,3.520485,3.669621,3.559877,3.584817,3.369332,5.0,21.0,0.238095
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,...,1.345078,2.419489,2.649331,2.551137,2.418449,2.591954,2.823423,3.0,23.0,0.130435
6,14,Saudi investor picks up the Savoy\n\nLondons f...,business,8,2.994622,3.269539,3.188601,1.911811,1.809835,2.697434,...,1.497516,2.869183,2.922051,2.793576,2.648925,2.989812,3.312860,2.0,11.0,0.181818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7016,7313,"Oh God,what an idiotic movie!Incredibly cheap ...",movie,0,0.868447,2.199045,2.616758,2.775151,2.566123,3.451856,...,3.129943,2.555954,1.973326,1.604109,3.342596,1.365076,3.004099,4.0,15.0,0.266667
7017,7314,Although the likeliness of someone focusing on...,movie,0,1.179555,2.352704,2.846943,2.361339,2.511536,3.481241,...,2.955696,2.751148,1.662250,1.845379,3.259588,1.718896,3.117846,7.0,34.0,0.205882
7018,7315,"OK, I would not normally watch a Farrelly brot...",movie,0,0.879528,2.180948,2.797818,2.564929,2.130065,3.268162,...,2.793543,2.632243,1.916686,1.534206,2.829822,1.416083,2.974245,8.0,39.0,0.205128
7019,7316,I give this movie 2 stars purely because of it...,movie,0,0.698967,2.086715,2.490488,2.322584,2.111093,3.286735,...,2.873902,2.375822,1.713674,1.606385,3.111119,1.003729,2.832663,1.0,8.0,0.125000
7022,7319,Piece of subtle art. Maybe a masterpiece. Doub...,movie,7,1.778338,2.169969,2.766120,2.585927,2.400287,3.402753,...,3.019366,2.711591,1.801625,1.637934,3.004033,1.672995,3.047235,3.0,25.0,0.120000

In [179]:
import numpy as np
post_test['attraction'] = np.where(post_test['mean_target'] >= mean_like, True, False)
post_test

,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,...,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,target_x,target_y,mean_target,attraction
0,1,UK economy facing major risks\n\nThe UK manufa...,business,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,...,2.856973,3.283484,3.328180,3.299252,3.274009,3.226359,2.0,14.0,0.142857,True
1,2,Aids and climate top Davos agenda\n\nClimate c...,business,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,...,2.653073,3.028255,3.160940,2.774500,3.260491,3.178570,2.0,26.0,0.076923,False
2,3,Asian quake hits European shares\n\nShares in ...,business,8,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,...,2.913700,3.102815,3.294351,2.775532,3.399966,3.126604,6.0,27.0,0.222222,True
3,4,India power shares jump on debut\n\nShares in ...,business,8,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,...,3.132410,3.520485,3.669621,3.559877,3.584817,3.369332,5.0,21.0,0.238095,True
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,...,2.419489,2.649331,2.551137,2.418449,2.591954,2.823423,3.0,23.0,0.130435,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7315,"OK, I would not normally watch a Farrelly brot...",movie,0,0.879528,2.180948,2.797818,2.564929,2.130065,3.268162,...,2.632243,1.916686,1.534206,2.829822,1.416083,2.974245,8.0,39.0,0.205128,True
7019,7316,I give this movie 2 stars purely because of it...,movie,0,0.698967,2.086715,2.490488,2.322584,2.111093,3.286735,...,2.375822,1.713674,1.606385,3.111119,1.003729,2.832663,1.0,8.0,0.125000,True
7020,7317,I cant believe this film was allowed to be mad...,movie,0,1.161841,2.444997,2.193800,2.647159,2.271674,3.361959,...,2.378414,2.133450,1.821000,3.014389,1.761077,2.676703,1.0,20.0,0.050000,False
7021,7318,The version I saw of this film was the Blockbu...,movie,13,1.423654,1.947482,3.242426,2.937189,2.261545,3.346242,...,3.061242,1.938101,1.043027,3.161317,1.028654,3.388523,2.0,19.0,0.105263,False
7022,7319,Piece of subtle art. Maybe a masterpiece. Doub...,movie,7,1.778338,2.169969,2.766120,2.585927,2.400287,3.402753,...,2.711591,1.801625,1.637934,3.004033,1.672995,3.047235,3.0,25.0,0.120000,True

In [180]:
post_test = post_test.drop(['target_x', 'target_y', 'mean_target'], axis =1)
post_test

,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction
0,1,UK economy facing major risks\n\nThe UK manufa...,business,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,1.969380,3.350282,1.552706,2.856973,3.283484,3.328180,3.299252,3.274009,3.226359,True
1,2,Aids and climate top Davos agenda\n\nClimate c...,business,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,1.947727,2.963042,1.431155,2.653073,3.028255,3.160940,2.774500,3.260491,3.178570,False
2,3,Asian quake hits European shares\n\nShares in ...,business,8,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,2.831849,2.970637,1.357996,2.913700,3.102815,3.294351,2.775532,3.399966,3.126604,True
3,4,India power shares jump on debut\n\nShares in ...,business,8,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,3.203395,3.670003,2.122464,3.132410,3.520485,3.669621,3.559877,3.584817,3.369332,True
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,2.673844,2.581019,1.345078,2.419489,2.649331,2.551137,2.418449,2.591954,2.823423,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7315,"OK, I would not normally watch a Farrelly brot...",movie,0,0.879528,2.180948,2.797818,2.564929,2.130065,3.268162,3.195646,1.614585,2.793543,2.632243,1.916686,1.534206,2.829822,1.416083,2.974245,True
7019,7316,I give this movie 2 stars purely because of it...,movie,0,0.698967,2.086715,2.490488,2.322584,2.111093,3.286735,3.083744,1.692232,2.873902,2.375822,1.713674,1.606385,3.111119,1.003729,2.832663,True
7020,7317,I cant believe this film was allowed to be mad...,movie,0,1.161841,2.444997,2.193800,2.647159,2.271674,3.361959,3.267648,1.826294,3.061269,2.378414,2.133450,1.821000,3.014389,1.761077,2.676703,False
7021,7318,The version I saw of this film was the Blockbu...,movie,13,1.423654,1.947482,3.242426,2.937189,2.261545,3.346242,3.379467,1.566741,3.147256,3.061242,1.938101,1.043027,3.161317,1.028654,3.388523,False
7022,7319,Piece of subtle art. Maybe a masterpiece. Doub...,movie,7,1.778338,2.169969,2.766120,2.585927,2.400287,3.402753,3.306942,1.207134,3.019366,2.711591,1.801625,1.637934,3.004033,1.672995,3.047235,True

In [181]:
post_test['attraction'] = post_test['attraction'].replace([True, False], [1,0])
post_test

,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction
0,1,UK economy facing major risks\n\nThe UK manufa...,business,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,1.969380,3.350282,1.552706,2.856973,3.283484,3.328180,3.299252,3.274009,3.226359,1
1,2,Aids and climate top Davos agenda\n\nClimate c...,business,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,1.947727,2.963042,1.431155,2.653073,3.028255,3.160940,2.774500,3.260491,3.178570,0
2,3,Asian quake hits European shares\n\nShares in ...,business,8,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,2.831849,2.970637,1.357996,2.913700,3.102815,3.294351,2.775532,3.399966,3.126604,1
3,4,India power shares jump on debut\n\nShares in ...,business,8,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,3.203395,3.670003,2.122464,3.132410,3.520485,3.669621,3.559877,3.584817,3.369332,1
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,2.673844,2.581019,1.345078,2.419489,2.649331,2.551137,2.418449,2.591954,2.823423,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7315,"OK, I would not normally watch a Farrelly brot...",movie,0,0.879528,2.180948,2.797818,2.564929,2.130065,3.268162,3.195646,1.614585,2.793543,2.632243,1.916686,1.534206,2.829822,1.416083,2.974245,1
7019,7316,I give this movie 2 stars purely because of it...,movie,0,0.698967,2.086715,2.490488,2.322584,2.111093,3.286735,3.083744,1.692232,2.873902,2.375822,1.713674,1.606385,3.111119,1.003729,2.832663,1
7020,7317,I cant believe this film was allowed to be mad...,movie,0,1.161841,2.444997,2.193800,2.647159,2.271674,3.361959,3.267648,1.826294,3.061269,2.378414,2.133450,1.821000,3.014389,1.761077,2.676703,0
7021,7318,The version I saw of this film was the Blockbu...,movie,13,1.423654,1.947482,3.242426,2.937189,2.261545,3.346242,3.379467,1.566741,3.147256,3.061242,1.938101,1.043027,3.161317,1.028654,3.388523,0
7022,7319,Piece of subtle art. Maybe a masterpiece. Doub...,movie,7,1.778338,2.169969,2.766120,2.585927,2.400287,3.402753,3.306942,1.207134,3.019366,2.711591,1.801625,1.637934,3.004033,1.672995,3.047235,1

# Новый признак (конец)

In [182]:
#ohe = pd.get_dummies(df_post['topic'], prefix='topic', drop_first=True)
#df_post = pd.concat((df_post.drop('topic', axis=1), ohe), axis=1)
#df_post

ohe = pd.get_dummies(post_test['topic'], prefix='topic', drop_first=True)
post_test = pd.concat((post_test.drop('topic', axis=1), ohe), axis=1)
post_test.head()

,post_id,text,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,...,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction,topic_covid,topic_entertainment,topic_movie,topic_politics,topic_sport,topic_tech
0,1,UK economy facing major risks\n\nThe UK manufa...,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,1.969380,...,3.299252,3.274009,3.226359,1,0,0,0,0,0,0
1,2,Aids and climate top Davos agenda\n\nClimate c...,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,1.947727,...,2.774500,3.260491,3.178570,0,0,0,0,0,0,0
2,3,Asian quake hits European shares\n\nShares in ...,8,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,2.831849,...,2.775532,3.399966,3.126604,1,0,0,0,0,0,0
3,4,India power shares jump on debut\n\nShares in ...,8,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,3.203395,...,3.559877,3.584817,3.369332,1,0,0,0,0,0,0
4,5,Lacroix label bought by US firm\n\nLuxury good...,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,2.673844,...,2.418449,2.591954,2.823423,1,0,0,0,0,0,0

In [241]:
df_feed.head()

            timestamp  user_id  post_id action  target
0 2021-10-13 11:32:51    33578     1187   view       0
1 2021-10-13 11:33:07    33578     5390   view       0
2 2021-10-13 11:35:53    33578     6724   view       0
3 2021-10-13 11:38:22    33578     1440   view       0
4 2021-10-13 11:40:43    33578     4071   view       0

In [184]:
#ohe = pd.get_dummies(df_feed['action'], prefix='action', drop_first=True)
#df_feed = pd.concat((df_feed.drop(['timestamp', 'action'], axis=1), ohe), axis=1)

In [242]:
df_feed = df_feed.drop(['timestamp', 'action'], axis=1)

In [188]:
df_feed

        user_id  post_id  target
0        101572     3460       0
1        101572     4955       0
2        101572     1832       0
3        101572     5614       0
4        101572     6916       0
...         ...      ...     ...
199995    80579       72       0
199996    80579      622       0
199997    80579     2771       0
199998    80579     3561       0
199999    80579     4483       0

[200000 rows x 3 columns]

In [243]:
df_user.corr()

,user_id,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,country_Switzerland,country_Turkey,country_Ukraine,exp_group_1,exp_group_2,exp_group_3,exp_group_4,os_iOS,source_organic
user_id,1.000000,-0.004867,0.003124,0.000896,0.001865,0.001883,-0.002903,-0.000900,-0.001217,0.001761,0.002605,0.001166,-0.001858,0.002634,-0.002667,-0.004300,-0.000823,-0.003752,0.837170
gender,-0.004867,1.000000,0.000582,0.003896,0.004688,0.002935,-0.002949,-0.004446,-0.002064,-0.002720,0.002615,0.002816,0.002687,-0.001397,0.001753,-0.002799,-0.001275,-0.004656,-0.004548
age,0.003124,0.000582,1.000000,0.001147,0.002760,0.003068,-0.000616,0.000400,0.000070,-0.001825,0.002325,0.002499,0.001420,0.001361,-0.002649,0.001283,-0.000978,0.001518,0.002195
country_Belarus,0.000896,0.003896,0.001147,1.000000,-0.004634,-0.004742,-0.014274,-0.020203,-0.004702,-0.382141,-0.004523,-0.014306,-0.033160,-0.000059,-0.001532,-0.002193,0.002621,-0.000621,0.003121
country_Cyprus,0.001865,0.004688,0.002760,-0.004634,1.000000,-0.001067,-0.003212,-0.004546,-0.001058,-0.085991,-0.001018,-0.003219,-0.007462,0.000001,-0.000462,0.004205,0.000565,-0.001041,0.000752
country_Estonia,0.001883,0.002935,0.003068,-0.004742,-0.001067,1.000000,-0.003287,-0.004652,-0.001083,-0.087993,-0.001042,-0.003294,-0.007636,0.002044,-0.000265,0.000121,-0.006234,-0.000553,0.001495
country_Finland,-0.002903,-0.002949,-0.000616,-0.014274,-0.003212,-0.003287,1.000000,-0.014004,-0.003259,-0.264889,-0.003135,-0.009916,-0.022986,0.000969,0.002095,-0.003579,0.000772,-0.002443,-0.003048
country_Kazakhstan,-0.000900,-0.004446,0.000400,-0.020203,-0.004546,-0.004652,-0.014004,1.000000,-0.004613,-0.374913,-0.004438,-0.014035,-0.032533,0.002070,-0.003649,0.001455,0.000787,0.002199,-0.000612
country_Latvia,-0.001217,-0.002064,0.000070,-0.004702,-0.001058,-0.001083,-0.003259,-0.004613,1.000000,-0.087248,-0.001033,-0.003266,-0.007571,-0.002339,-0.000455,0.000871,0.000090,0.001817,0.000013
country_Russia,0.001761,-0.002720,-0.001825,-0.382141,-0.085991,-0.087993,-0.264889,-0.374913,-0.087248,1.000000,-0.083941,-0.265474,-0.615360,0.000681,0.002033,-0.000339,-0.002478,-0.000263,0.001347
country_Switzerland,0.002605,0.002615,0.002325,-0.004523,-0.001018,-0.001042,-0.003135,-0.004438,-0.001033,-0.083941,1.000000,-0.003142,-0.007284,-0.002625,0.000792,0.000716,-0.000108,-0.000330,0.001178
country_Turkey,0.001166,0.002816,0.002499,-0.014306,-0.003219,-0.003294,-0.009916,-0.014035,-0.003266,-0.265474,-0.003142,1.000000,-0.023036,-0.000802,-0.001076,0.001635,-0.000690,-0.004318,-0.002226
country_Ukraine,-0.001858,0.002687,0.001420,-0.033160,-0.007462,-0.007636,-0.022986,-0.032533,-0.007571,-0.615360,-0.007284,-0.023036,1.000000,0.000667,-0.001483,0.001113,0.003182,0.002447,-0.001412
exp_group_1,0.002634,-0.001397,0.001361,-0.000059,0.000001,0.002044,0.000969,0.002070,-0.002339,0.000681,-0.002625,-0.000802,0.000667,1.000000,-0.249856,-0.250593,-0.249129,-0.001270,0.003892
exp_group_2,-0.002667,0.001753,-0.002649,-0.001532,-0.000462,-0.000265,0.002095,-0.003649,-0.000455,0.002033,0.000792,-0.001076,-0.001483,-0.249856,1.000000,-0.250478,-0.249014,0.002404,-0.003156
exp_group_3,-0.004300,-0.002799,0.001283,-0.002193,0.004205,0.000121,-0.003579,0.001455,0.000871,-0.000339,0.000716,0.001635,0.001113,-0.250593,-0.250478,1.000000,-0.249749,-0.001351,-0.003815
exp_group_4,-0.000823,-0.001275,-0.000978,0.002621,0.000565,-0.006234,0.000772,0.000787,0.000090,-0.002478,-0.000108,-0.000690,0.003182,-0.249129,-0.249014,-0.249749,1.000000,-0.000220,-0.000428
os_iOS,-0.003752,-0.004656,0.001518,-0.000621,-0.001041,-0.000553,-0.002443,0.002199,0.001817,-0.000263,-0.000330,-0.004318,0.002447,-0.001270,0.002404,-0.001351,-0.000220,1.000000,-0.002674
source_organic,0.837170,-0.004548,0.002195,0.003121,0.000752,0.001495,-0.003048,-0.000612,0.000013,0.001347,0.001178,-0.002226,-0.001412,0.003892,-0.003156,-0.003815,-0.000428,-0.002674,1.000000

In [244]:
#Проверяем типы данных в датафреймах
print(df_user.dtypes)
print()
print(df_post.dtypes)
print()
print(df_feed.dtypes)

user_id                int64
gender                 int64
age                    int64
country_Belarus        uint8
country_Cyprus         uint8
country_Estonia        uint8
country_Finland        uint8
country_Kazakhstan     uint8
country_Latvia         uint8
country_Russia         uint8
country_Switzerland    uint8
country_Turkey         uint8
country_Ukraine        uint8
exp_group_1            uint8
exp_group_2            uint8
exp_group_3            uint8
exp_group_4            uint8
os_iOS                 uint8
source_organic         uint8
dtype: object

post_id     int64
text       object
topic      object
dtype: object

user_id    int64
post_id    int64
target     int64
dtype: object

In [245]:
#Проверяем пропуски
#df_user.isna().sum() #нет пропусков
#df_post.isna().sum() #нет пропусков
df_feed.isna().sum() #нет пропусков

user_id    0
post_id    0
target     0
dtype: int64

In [246]:
#df_feed.groupby(['user_id', 'post_id'],as_index=False).agg({'target':'sum','action':'sum'})

In [247]:
post_test.head()

,post_id,text,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,...,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction,topic_covid,topic_entertainment,topic_movie,topic_politics,topic_sport,topic_tech
0,1,UK economy facing major risks\n\nThe UK manufa...,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,1.969380,...,3.299252,3.274009,3.226359,1,0,0,0,0,0,0
1,2,Aids and climate top Davos agenda\n\nClimate c...,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,1.947727,...,2.774500,3.260491,3.178570,0,0,0,0,0,0,0
2,3,Asian quake hits European shares\n\nShares in ...,8,3.206180,3.420908,3.228868,2.183235,2.723449,3.286630,2.831849,...,2.775532,3.399966,3.126604,1,0,0,0,0,0,0
3,4,India power shares jump on debut\n\nShares in ...,8,3.616450,2.843541,3.649253,2.582405,3.227175,3.933870,3.203395,...,3.559877,3.584817,3.369332,1,0,0,0,0,0,0
4,5,Lacroix label bought by US firm\n\nLuxury good...,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,2.673844,...,2.418449,2.591954,2.823423,1,0,0,0,0,0,0

In [248]:
test = df_user.merge(df_feed, on = 'user_id', how = 'left').fillna(0)

#test = test[test['post_id'] != 'empty']

test = test.merge(post_test, on = 'post_id').fillna(0)
test = test.drop('text', axis=1)
test
#df_feed[df_feed['user_id']==120098].merge(df_post, on = 'post_id', how = 'left')

,user_id,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,...,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction,topic_covid,topic_entertainment,topic_movie,topic_politics,topic_sport,topic_tech
0,12421,1,34,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
1,12421,1,34,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
2,12439,0,27,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
3,12472,1,39,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
4,12472,1,39,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,167248,0,35,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499996,167261,0,15,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499997,167268,0,47,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499998,167268,0,47,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499999,167278,0,17,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0

In [249]:
col_to_int = ['post_id', 'target', 'topic_covid', 'topic_entertainment',
               'topic_movie', 'topic_politics', 'topic_sport', 'topic_tech'] #'action_view' убран
test[col_to_int] = test[col_to_int].astype(int)
#test.nunique()
test

,user_id,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,...,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction,topic_covid,topic_entertainment,topic_movie,topic_politics,topic_sport,topic_tech
0,12421,1,34,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
1,12421,1,34,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
2,12439,0,27,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
3,12472,1,39,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
4,12472,1,39,0,0,0,0,0,0,1,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,167248,0,35,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499996,167261,0,15,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499997,167268,0,47,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499998,167268,0,47,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499999,167278,0,17,0,0,0,0,0,0,1,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0

In [250]:
test = test.drop(['user_id', 'post_id'], axis=1)
test

,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,country_Switzerland,...,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction,topic_covid,topic_entertainment,topic_movie,topic_politics,topic_sport,topic_tech
0,1,34,0,0,0,0,0,0,1,0,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
1,1,34,0,0,0,0,0,0,1,0,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
2,0,27,0,0,0,0,0,0,1,0,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
3,1,39,0,0,0,0,0,0,1,0,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
4,1,39,0,0,0,0,0,0,1,0,...,2.954602,1.596257,3.105802,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,0,35,0,0,0,0,0,0,1,0,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499996,0,15,0,0,0,0,0,0,1,0,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499997,0,47,0,0,0,0,0,0,1,0,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499998,0,47,0,0,0,0,0,0,1,0,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0
499999,0,17,0,0,0,0,0,0,1,0,...,3.140694,1.048808,3.071775,1,0,0,1,0,0,0

# Тестируем работу конката при запросе

In [251]:
test_row = df_user.iloc[[0]]
test_row

,user_id,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,country_Switzerland,country_Turkey,country_Ukraine,exp_group_1,exp_group_2,exp_group_3,exp_group_4,os_iOS,source_organic
0,200,1,34,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0

In [252]:
df_user[df_user['user_id'] == 200]

,user_id,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,country_Switzerland,country_Turkey,country_Ukraine,exp_group_1,exp_group_2,exp_group_3,exp_group_4,os_iOS,source_organic
0,200,1,34,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0

In [253]:
#df_user(df_user['user_id'] == 200)
test_row = df_user.iloc[[0]].drop('user_id', axis=1)
test_row

,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,country_Switzerland,country_Turkey,country_Ukraine,exp_group_1,exp_group_2,exp_group_3,exp_group_4,os_iOS,source_organic
0,1,34,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0

In [254]:
all_posts = pd.concat((test_row, post_test.drop(['text'], axis=1)), axis=1).fillna(method='ffill')
all_posts

,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,country_Switzerland,...,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction,topic_covid,topic_entertainment,topic_movie,topic_politics,topic_sport,topic_tech
0,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.299252,3.274009,3.226359,1,0,0,0,0,0,0
1,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,2.774500,3.260491,3.178570,0,0,0,0,0,0,0
2,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,2.775532,3.399966,3.126604,1,0,0,0,0,0,0
3,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.559877,3.584817,3.369332,1,0,0,0,0,0,0
4,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,2.418449,2.591954,2.823423,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,2.829822,1.416083,2.974245,1,0,0,1,0,0,0
7019,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.111119,1.003729,2.832663,1,0,0,1,0,0,0
7020,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.014389,1.761077,2.676703,0,0,0,1,0,0,0
7021,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.161317,1.028654,3.388523,0,0,0,1,0,0,0
7022,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.004033,1.672995,3.047235,1,0,0,1,0,0,0

# СТРОИМ МОДЕЛЬ

In [255]:
from sklearn.model_selection import train_test_split

X = test.drop(['target'], axis=1)
y = test['target']

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.25, 
                                                    random_state=1)

#Вариант 1
#from sklearn.pipeline import Pipeline
#from sklearn.preprocessing import StandardScaler
#from sklearn.linear_model import Lasso

#from sklearn.metrics import accuracy_score


#pipe = Pipeline(
#    [
#        ('transformer',
#         StandardScaler()),
#                 
#        ('estimator',
#         Lasso())
#    ]
#)

#pipe.fit(X_train, y_train)
#round(accuracy_score(y_test, pipe.predict(X_test)), 3)

In [256]:
#Вариант 2
from catboost import CatBoostClassifier

model = CatBoostClassifier(learning_rate=0.02)

model.fit(X_train, y_train)

0:	learn: 0.6767129	total: 54.8ms	remaining: 54.8s
1:	learn: 0.6611702	total: 85.8ms	remaining: 42.8s
2:	learn: 0.6462094	total: 115ms	remaining: 38.4s
3:	learn: 0.6319777	total: 146ms	remaining: 36.4s
4:	learn: 0.6185180	total: 176ms	remaining: 35s
5:	learn: 0.6056953	total: 205ms	remaining: 34s
6:	learn: 0.5934656	total: 237ms	remaining: 33.6s
7:	learn: 0.5817909	total: 267ms	remaining: 33.1s
8:	learn: 0.5707095	total: 299ms	remaining: 32.9s
9:	learn: 0.5601260	total: 331ms	remaining: 32.8s
10:	learn: 0.5500722	total: 362ms	remaining: 32.6s
11:	learn: 0.5404454	total: 392ms	remaining: 32.3s
12:	learn: 0.5312993	total: 423ms	remaining: 32.1s
13:	learn: 0.5226146	total: 453ms	remaining: 31.9s
14:	learn: 0.5142049	total: 488ms	remaining: 32.1s
15:	learn: 0.5062632	total: 520ms	remaining: 32s
16:	learn: 0.4987212	total: 553ms	remaining: 32s
17:	learn: 0.4915639	total: 582ms	remaining: 31.8s
18:	learn: 0.4845441	total: 611ms	remaining: 31.5s
19:	learn: 0.4778698	total: 641ms	remaining: 31.4s
20:	learn: 0.4716024	total: 673ms	remaining: 31.4s
21:	learn: 0.4656441	total: 705ms	remaining: 31.3s
22:	learn: 0.4600029	total: 734ms	remaining: 31.2s
23:	learn: 0.4545867	total: 767ms	remaining: 31.2s
24:	learn: 0.4494358	total: 799ms	remaining: 31.2s
25:	learn: 0.4445718	total: 832ms	remaining: 31.2s
26:	learn: 0.4399478	total: 863ms	remaining: 31.1s
27:	learn: 0.4354486	total: 897ms	remaining: 31.1s
28:	learn: 0.4311384	total: 929ms	remaining: 31.1s
29:	learn: 0.4271197	total: 958ms	remaining: 31s
30:	learn: 0.4233023	total: 990ms	remaining: 30.9s
31:	learn: 0.4196415	total: 1.02s	remaining: 30.8s
32:	learn: 0.4161747	total: 1.05s	remaining: 30.8s
33:	learn: 0.4127736	total: 1.08s	remaining: 30.8s
34:	learn: 0.4095014	total: 1.11s	remaining: 30.7s
35:	learn: 0.4064905	total: 1.15s	remaining: 30.8s
36:	learn: 0.4035767	total: 1.18s	remaining: 30.7s
37:	learn: 0.4007458	total: 1.21s	remaining: 30.6s
38:	learn: 0.3981423	total: 1.24s	remaining: 30.5s
39:	learn: 0.3956125	total: 1.27s	remaining: 30.4s
40:	learn: 0.3930939	total: 1.3s	remaining: 30.5s
41:	learn: 0.3908294	total: 1.33s	remaining: 30.4s
42:	learn: 0.3886447	total: 1.37s	remaining: 30.4s
43:	learn: 0.3865693	total: 1.4s	remaining: 30.4s
44:	learn: 0.3845881	total: 1.43s	remaining: 30.3s
45:	learn: 0.3825892	total: 1.46s	remaining: 30.2s
46:	learn: 0.3807332	total: 1.49s	remaining: 30.2s
47:	learn: 0.3788968	total: 1.52s	remaining: 30.2s
48:	learn: 0.3772359	total: 1.55s	remaining: 30.1s
49:	learn: 0.3755818	total: 1.59s	remaining: 30.1s
50:	learn: 0.3740347	total: 1.62s	remaining: 30.1s
51:	learn: 0.3725443	total: 1.65s	remaining: 30s
52:	learn: 0.3710746	total: 1.68s	remaining: 30s
53:	learn: 0.3697549	total: 1.71s	remaining: 29.9s
54:	learn: 0.3685106	total: 1.74s	remaining: 29.9s
55:	learn: 0.3673294	total: 1.77s	remaining: 29.8s
56:	learn: 0.3660870	total: 1.8s	remaining: 29.8s
57:	learn: 0.3649140	total: 1.83s	remaining: 29.7s
58:	learn: 0.3638846	total: 1.86s	remaining: 29.6s
59:	learn: 0.3628690	total: 1.89s	remaining: 29.6s
60:	learn: 0.3618608	total: 1.92s	remaining: 29.6s
61:	learn: 0.3609313	total: 1.95s	remaining: 29.6s
62:	learn: 0.3600430	total: 1.98s	remaining: 29.5s
63:	learn: 0.3590899	total: 2.02s	remaining: 29.5s
64:	learn: 0.3582620	total: 2.05s	remaining: 29.4s
65:	learn: 0.3574100	total: 2.08s	remaining: 29.4s
66:	learn: 0.3566571	total: 2.11s	remaining: 29.4s
67:	learn: 0.3559256	total: 2.14s	remaining: 29.3s
68:	learn: 0.3551996	total: 2.17s	remaining: 29.3s
69:	learn: 0.3544658	total: 2.2s	remaining: 29.3s
70:	learn: 0.3538384	total: 2.23s	remaining: 29.2s
71:	learn: 0.3532263	total: 2.26s	remaining: 29.2s
72:	learn: 0.3526608	total: 2.29s	remaining: 29.1s
73:	learn: 0.3520387	total: 2.33s	remaining: 29.1s
74:	learn: 0.3514920	total: 2.36s	remaining: 29.1s
75:	learn: 0.3509269	total: 2.39s	remaining: 29.1s
76:	learn: 0.3503961	total: 2.42s	remaining: 29.1s
77:	learn: 0.3499232	total: 2.46s	remaining: 29s
78:	learn: 0.3494688	total: 2.49s	remaining: 29s
79:	learn: 0.3489997	total: 2.52s	remaining: 29s
80:	learn: 0.3485461	total: 2.55s	remaining: 29s
81:	learn: 0.3480973	total: 2.59s	remaining: 29s
82:	learn: 0.3477124	total: 2.62s	remaining: 29s
83:	learn: 0.3473653	total: 2.66s	remaining: 29s
84:	learn: 0.3469484	total: 2.69s	remaining: 29s
85:	learn: 0.3465973	total: 2.72s	remaining: 28.9s
86:	learn: 0.3462711	total: 2.75s	remaining: 28.9s
87:	learn: 0.3459627	total: 2.78s	remaining: 28.8s
88:	learn: 0.3456311	total: 2.81s	remaining: 28.8s
89:	learn: 0.3453047	total: 2.85s	remaining: 28.8s
90:	learn: 0.3450119	total: 2.88s	remaining: 28.8s
91:	learn: 0.3447163	total: 2.92s	remaining: 28.8s
92:	learn: 0.3444805	total: 2.96s	remaining: 28.8s
93:	learn: 0.3442229	total: 2.99s	remaining: 28.8s
94:	learn: 0.3439670	total: 3.03s	remaining: 28.9s
95:	learn: 0.3437118	total: 3.06s	remaining: 28.9s
96:	learn: 0.3434427	total: 3.1s	remaining: 28.8s
97:	learn: 0.3432233	total: 3.13s	remaining: 28.8s
98:	learn: 0.3430222	total: 3.16s	remaining: 28.8s
99:	learn: 0.3428170	total: 3.19s	remaining: 28.7s
100:	learn: 0.3426370	total: 3.22s	remaining: 28.7s
101:	learn: 0.3424349	total: 3.25s	remaining: 28.6s
102:	learn: 0.3422195	total: 3.29s	remaining: 28.6s
103:	learn: 0.3420235	total: 3.32s	remaining: 28.6s
104:	learn: 0.3418223	total: 3.36s	remaining: 28.6s
105:	learn: 0.3416463	total: 3.39s	remaining: 28.6s
106:	learn: 0.3415174	total: 3.42s	remaining: 28.5s
107:	learn: 0.3413728	total: 3.44s	remaining: 28.5s
108:	learn: 0.3412100	total: 3.48s	remaining: 28.4s
109:	learn: 0.3410516	total: 3.51s	remaining: 28.4s
110:	learn: 0.3409101	total: 3.54s	remaining: 28.3s
111:	learn: 0.3407820	total: 3.57s	remaining: 28.3s
112:	learn: 0.3406270	total: 3.6s	remaining: 28.3s
113:	learn: 0.3404887	total: 3.64s	remaining: 28.3s
114:	learn: 0.3403774	total: 3.67s	remaining: 28.3s
115:	learn: 0.3402506	total: 3.7s	remaining: 28.2s
116:	learn: 0.3401214	total: 3.73s	remaining: 28.2s
117:	learn: 0.3400121	total: 3.76s	remaining: 28.1s
118:	learn: 0.3398984	total: 3.79s	remaining: 28.1s
119:	learn: 0.3398023	total: 3.83s	remaining: 28.1s
120:	learn: 0.3397060	total: 3.85s	remaining: 28s
121:	learn: 0.3395919	total: 3.89s	remaining: 28s
122:	learn: 0.3394834	total: 3.92s	remaining: 27.9s
123:	learn: 0.3394058	total: 3.95s	remaining: 27.9s
124:	learn: 0.3392983	total: 3.98s	remaining: 27.9s
125:	learn: 0.3391959	total: 4.02s	remaining: 27.9s
126:	learn: 0.3391120	total: 4.05s	remaining: 27.9s
127:	learn: 0.3390434	total: 4.08s	remaining: 27.8s
128:	learn: 0.3389613	total: 4.12s	remaining: 27.8s
129:	learn: 0.3388744	total: 4.15s	remaining: 27.8s
130:	learn: 0.3388236	total: 4.18s	remaining: 27.8s
131:	learn: 0.3387526	total: 4.22s	remaining: 27.7s
132:	learn: 0.3386788	total: 4.25s	remaining: 27.7s
133:	learn: 0.3386177	total: 4.28s	remaining: 27.7s
134:	learn: 0.3385606	total: 4.32s	remaining: 27.6s
135:	learn: 0.3385027	total: 4.35s	remaining: 27.6s
136:	learn: 0.3384333	total: 4.38s	remaining: 27.6s
137:	learn: 0.3383697	total: 4.42s	remaining: 27.6s
138:	learn: 0.3383206	total: 4.45s	remaining: 27.6s
139:	learn: 0.3382750	total: 4.49s	remaining: 27.6s
140:	learn: 0.3382360	total: 4.52s	remaining: 27.5s
141:	learn: 0.3382055	total: 4.54s	remaining: 27.4s
142:	learn: 0.3381429	total: 4.58s	remaining: 27.4s
143:	learn: 0.3380985	total: 4.61s	remaining: 27.4s
144:	learn: 0.3380456	total: 4.64s	remaining: 27.4s
145:	learn: 0.3379756	total: 4.67s	remaining: 27.4s
146:	learn: 0.3379236	total: 4.71s	remaining: 27.3s
147:	learn: 0.3378772	total: 4.74s	remaining: 27.3s
148:	learn: 0.3378440	total: 4.77s	remaining: 27.3s
149:	learn: 0.3377992	total: 4.8s	remaining: 27.2s
150:	learn: 0.3377444	total: 4.84s	remaining: 27.2s
151:	learn: 0.3376965	total: 4.87s	remaining: 27.2s
152:	learn: 0.3376689	total: 4.9s	remaining: 27.2s
153:	learn: 0.3376423	total: 4.93s	remaining: 27.1s
154:	learn: 0.3375928	total: 4.96s	remaining: 27.1s
155:	learn: 0.3375442	total: 5s	remaining: 27s
156:	learn: 0.3375144	total: 5.02s	remaining: 27s
157:	learn: 0.3374692	total: 5.05s	remaining: 26.9s
158:	learn: 0.3374295	total: 5.08s	remaining: 26.9s
159:	learn: 0.3373785	total: 5.12s	remaining: 26.9s
160:	learn: 0.3373537	total: 5.15s	remaining: 26.9s
161:	learn: 0.3373165	total: 5.18s	remaining: 26.8s
162:	learn: 0.3372877	total: 5.22s	remaining: 26.8s
163:	learn: 0.3372429	total: 5.25s	remaining: 26.8s
164:	learn: 0.3372139	total: 5.28s	remaining: 26.7s
165:	learn: 0.3371865	total: 5.32s	remaining: 26.7s
166:	learn: 0.3371352	total: 5.35s	remaining: 26.7s

167:	learn: 0.3371009	total: 5.38s	remaining: 26.7s
168:	learn: 0.3370592	total: 5.42s	remaining: 26.6s
169:	learn: 0.3370409	total: 5.45s	remaining: 26.6s
170:	learn: 0.3370144	total: 5.48s	remaining: 26.6s
171:	learn: 0.3369888	total: 5.52s	remaining: 26.6s
172:	learn: 0.3369621	total: 5.55s	remaining: 26.5s
173:	learn: 0.3369267	total: 5.58s	remaining: 26.5s
174:	learn: 0.3369019	total: 5.63s	remaining: 26.5s
175:	learn: 0.3368721	total: 5.66s	remaining: 26.5s
176:	learn: 0.3368272	total: 5.69s	remaining: 26.5s
177:	learn: 0.3368075	total: 5.72s	remaining: 26.4s
178:	learn: 0.3367877	total: 5.75s	remaining: 26.4s
179:	learn: 0.3367605	total: 5.79s	remaining: 26.4s
180:	learn: 0.3367231	total: 5.82s	remaining: 26.4s
181:	learn: 0.3366881	total: 5.86s	remaining: 26.3s
182:	learn: 0.3366507	total: 5.89s	remaining: 26.3s
183:	learn: 0.3366310	total: 5.92s	remaining: 26.3s
184:	learn: 0.3366031	total: 5.95s	remaining: 26.2s
185:	learn: 0.3365783	total: 5.99s	remaining: 26.2s
186:	learn: 0.3365479	total: 6.02s	remaining: 26.2s
187:	learn: 0.3365216	total: 6.05s	remaining: 26.1s
188:	learn: 0.3364983	total: 6.09s	remaining: 26.1s
189:	learn: 0.3364798	total: 6.12s	remaining: 26.1s
190:	learn: 0.3364435	total: 6.15s	remaining: 26s
191:	learn: 0.3364188	total: 6.18s	remaining: 26s
192:	learn: 0.3364040	total: 6.22s	remaining: 26s
193:	learn: 0.3363892	total: 6.25s	remaining: 26s
194:	learn: 0.3363690	total: 6.29s	remaining: 26s
195:	learn: 0.3363525	total: 6.32s	remaining: 25.9s
196:	learn: 0.3363246	total: 6.35s	remaining: 25.9s
197:	learn: 0.3363022	total: 6.38s	remaining: 25.8s
198:	learn: 0.3362811	total: 6.41s	remaining: 25.8s
199:	learn: 0.3362636	total: 6.44s	remaining: 25.8s
200:	learn: 0.3362520	total: 6.48s	remaining: 25.7s
201:	learn: 0.3362426	total: 6.51s	remaining: 25.7s
202:	learn: 0.3362292	total: 6.54s	remaining: 25.7s
203:	learn: 0.3362023	total: 6.58s	remaining: 25.7s
204:	learn: 0.3361924	total: 6.61s	remaining: 25.7s
205:	learn: 0.3361715	total: 6.65s	remaining: 25.6s
206:	learn: 0.3361531	total: 6.68s	remaining: 25.6s
207:	learn: 0.3361424	total: 6.71s	remaining: 25.6s
208:	learn: 0.3361296	total: 6.74s	remaining: 25.5s
209:	learn: 0.3361178	total: 6.77s	remaining: 25.5s
210:	learn: 0.3361032	total: 6.8s	remaining: 25.4s
211:	learn: 0.3360900	total: 6.83s	remaining: 25.4s
212:	learn: 0.3360684	total: 6.86s	remaining: 25.4s
213:	learn: 0.3360567	total: 6.89s	remaining: 25.3s
214:	learn: 0.3360240	total: 6.92s	remaining: 25.3s
215:	learn: 0.3360016	total: 6.95s	remaining: 25.2s
216:	learn: 0.3359905	total: 6.98s	remaining: 25.2s
217:	learn: 0.3359767	total: 7.02s	remaining: 25.2s
218:	learn: 0.3359636	total: 7.05s	remaining: 25.1s
219:	learn: 0.3359424	total: 7.08s	remaining: 25.1s
220:	learn: 0.3359291	total: 7.12s	remaining: 25.1s
221:	learn: 0.3359202	total: 7.15s	remaining: 25.1s
222:	learn: 0.3359047	total: 7.18s	remaining: 25s
223:	learn: 0.3358823	total: 7.22s	remaining: 25s
224:	learn: 0.3358655	total: 7.25s	remaining: 25s
225:	learn: 0.3358532	total: 7.29s	remaining: 25s
226:	learn: 0.3358456	total: 7.32s	remaining: 24.9s
227:	learn: 0.3358350	total: 7.35s	remaining: 24.9s
228:	learn: 0.3358080	total: 7.38s	remaining: 24.9s
229:	learn: 0.3357974	total: 7.41s	remaining: 24.8s
230:	learn: 0.3357916	total: 7.45s	remaining: 24.8s
231:	learn: 0.3357838	total: 7.48s	remaining: 24.8s
232:	learn: 0.3357745	total: 7.51s	remaining: 24.7s
233:	learn: 0.3357630	total: 7.54s	remaining: 24.7s
234:	learn: 0.3357502	total: 7.57s	remaining: 24.7s
235:	learn: 0.3357369	total: 7.6s	remaining: 24.6s
236:	learn: 0.3357271	total: 7.64s	remaining: 24.6s
237:	learn: 0.3357054	total: 7.67s	remaining: 24.6s
238:	learn: 0.3356948	total: 7.71s	remaining: 24.5s
239:	learn: 0.3356853	total: 7.74s	remaining: 24.5s
240:	learn: 0.3356757	total: 7.77s	remaining: 24.5s
241:	learn: 0.3356630	total: 7.8s	remaining: 24.4s
242:	learn: 0.3356454	total: 7.83s	remaining: 24.4s
243:	learn: 0.3356279	total: 7.87s	remaining: 24.4s
244:	learn: 0.3356023	total: 7.9s	remaining: 24.4s
245:	learn: 0.3355810	total: 7.93s	remaining: 24.3s
246:	learn: 0.3355738	total: 7.96s	remaining: 24.3s
247:	learn: 0.3355538	total: 8s	remaining: 24.2s
248:	learn: 0.3355491	total: 8.03s	remaining: 24.2s
249:	learn: 0.3355279	total: 8.06s	remaining: 24.2s
250:	learn: 0.3355208	total: 8.1s	remaining: 24.2s
251:	learn: 0.3355133	total: 8.13s	remaining: 24.1s
252:	learn: 0.3355043	total: 8.16s	remaining: 24.1s
253:	learn: 0.3354831	total: 8.19s	remaining: 24s
254:	learn: 0.3354675	total: 8.22s	remaining: 24s
255:	learn: 0.3354606	total: 8.25s	remaining: 24s
256:	learn: 0.3354374	total: 8.28s	remaining: 23.9s
257:	learn: 0.3354214	total: 8.31s	remaining: 23.9s
258:	learn: 0.3354129	total: 8.34s	remaining: 23.9s
259:	learn: 0.3353914	total: 8.37s	remaining: 23.8s
260:	learn: 0.3353882	total: 8.4s	remaining: 23.8s
261:	learn: 0.3353802	total: 8.43s	remaining: 23.8s
262:	learn: 0.3353691	total: 8.46s	remaining: 23.7s
263:	learn: 0.3353589	total: 8.5s	remaining: 23.7s
264:	learn: 0.3353437	total: 8.53s	remaining: 23.7s
265:	learn: 0.3353333	total: 8.56s	remaining: 23.6s
266:	learn: 0.3353196	total: 8.6s	remaining: 23.6s
267:	learn: 0.3353111	total: 8.63s	remaining: 23.6s
268:	learn: 0.3352984	total: 8.67s	remaining: 23.6s
269:	learn: 0.3352868	total: 8.7s	remaining: 23.5s
270:	learn: 0.3352772	total: 8.72s	remaining: 23.5s
271:	learn: 0.3352643	total: 8.76s	remaining: 23.4s
272:	learn: 0.3352503	total: 8.79s	remaining: 23.4s
273:	learn: 0.3352323	total: 8.82s	remaining: 23.4s
274:	learn: 0.3352248	total: 8.86s	remaining: 23.4s
275:	learn: 0.3352162	total: 8.89s	remaining: 23.3s
276:	learn: 0.3352089	total: 8.92s	remaining: 23.3s
277:	learn: 0.3351983	total: 8.95s	remaining: 23.3s
278:	learn: 0.3351876	total: 8.99s	remaining: 23.2s
279:	learn: 0.3351800	total: 9.02s	remaining: 23.2s
280:	learn: 0.3351747	total: 9.05s	remaining: 23.2s
281:	learn: 0.3351712	total: 9.08s	remaining: 23.1s
282:	learn: 0.3351590	total: 9.11s	remaining: 23.1s
283:	learn: 0.3351460	total: 9.14s	remaining: 23s
284:	learn: 0.3351303	total: 9.17s	remaining: 23s
285:	learn: 0.3351138	total: 9.21s	remaining: 23s
286:	learn: 0.3351053	total: 9.24s	remaining: 23s
287:	learn: 0.3350954	total: 9.27s	remaining: 22.9s
288:	learn: 0.3350836	total: 9.3s	remaining: 22.9s
289:	learn: 0.3350759	total: 9.34s	remaining: 22.9s
290:	learn: 0.3350675	total: 9.37s	remaining: 22.8s
291:	learn: 0.3350576	total: 9.4s	remaining: 22.8s
292:	learn: 0.3350394	total: 9.43s	remaining: 22.8s
293:	learn: 0.3350261	total: 9.46s	remaining: 22.7s
294:	learn: 0.3350209	total: 9.49s	remaining: 22.7s
295:	learn: 0.3350164	total: 9.52s	remaining: 22.6s
296:	learn: 0.3350108	total: 9.55s	remaining: 22.6s
297:	learn: 0.3350052	total: 9.59s	remaining: 22.6s
298:	learn: 0.3349972	total: 9.62s	remaining: 22.6s
299:	learn: 0.3349842	total: 9.65s	remaining: 22.5s
300:	learn: 0.3349736	total: 9.69s	remaining: 22.5s
301:	learn: 0.3349607	total: 9.73s	remaining: 22.5s
302:	learn: 0.3349501	total: 9.76s	remaining: 22.4s
303:	learn: 0.3349396	total: 9.79s	remaining: 22.4s
304:	learn: 0.3349301	total: 9.82s	remaining: 22.4s
305:	learn: 0.3349207	total: 9.86s	remaining: 22.4s
306:	learn: 0.3349109	total: 9.89s	remaining: 22.3s
307:	learn: 0.3348949	total: 9.92s	remaining: 22.3s
308:	learn: 0.3348807	total: 9.96s	remaining: 22.3s
309:	learn: 0.3348714	total: 9.99s	remaining: 22.2s
310:	learn: 0.3348625	total: 10s	remaining: 22.2s
311:	learn: 0.3348503	total: 10.1s	remaining: 22.2s
312:	learn: 0.3348457	total: 10.1s	remaining: 22.1s
313:	learn: 0.3348414	total: 10.1s	remaining: 22.1s
314:	learn: 0.3348311	total: 10.1s	remaining: 22.1s
315:	learn: 0.3348251	total: 10.2s	remaining: 22s
316:	learn: 0.3348124	total: 10.2s	remaining: 22s
317:	learn: 0.3348084	total: 10.2s	remaining: 22s
318:	learn: 0.3347994	total: 10.3s	remaining: 21.9s
319:	learn: 0.3347922	total: 10.3s	remaining: 21.9s
320:	learn: 0.3347864	total: 10.3s	remaining: 21.9s
321:	learn: 0.3347710	total: 10.4s	remaining: 21.8s
322:	learn: 0.3347640	total: 10.4s	remaining: 21.8s
323:	learn: 0.3347612	total: 10.4s	remaining: 21.8s
324:	learn: 0.3347575	total: 10.5s	remaining: 21.7s
325:	learn: 0.3347483	total: 10.5s	remaining: 21.7s
326:	learn: 0.3347442	total: 10.5s	remaining: 21.7s

327:	learn: 0.3347359	total: 10.6s	remaining: 21.6s
328:	learn: 0.3347288	total: 10.6s	remaining: 21.6s
329:	learn: 0.3347177	total: 10.6s	remaining: 21.6s
330:	learn: 0.3347142	total: 10.6s	remaining: 21.5s
331:	learn: 0.3346995	total: 10.7s	remaining: 21.5s
332:	learn: 0.3346900	total: 10.7s	remaining: 21.4s
333:	learn: 0.3346815	total: 10.7s	remaining: 21.4s
334:	learn: 0.3346731	total: 10.8s	remaining: 21.4s
335:	learn: 0.3346625	total: 10.8s	remaining: 21.3s
336:	learn: 0.3346573	total: 10.8s	remaining: 21.3s
337:	learn: 0.3346536	total: 10.9s	remaining: 21.3s
338:	learn: 0.3346458	total: 10.9s	remaining: 21.2s
339:	learn: 0.3346416	total: 10.9s	remaining: 21.2s
340:	learn: 0.3346364	total: 11s	remaining: 21.2s
341:	learn: 0.3346262	total: 11s	remaining: 21.2s
342:	learn: 0.3346167	total: 11s	remaining: 21.1s
343:	learn: 0.3346019	total: 11.1s	remaining: 21.1s
344:	learn: 0.3345970	total: 11.1s	remaining: 21.1s
345:	learn: 0.3345936	total: 11.1s	remaining: 21s
346:	learn: 0.3345839	total: 11.2s	remaining: 21s
347:	learn: 0.3345763	total: 11.2s	remaining: 21s
348:	learn: 0.3345706	total: 11.2s	remaining: 20.9s
349:	learn: 0.3345660	total: 11.3s	remaining: 20.9s
350:	learn: 0.3345619	total: 11.3s	remaining: 20.9s
351:	learn: 0.3345590	total: 11.3s	remaining: 20.8s
352:	learn: 0.3345558	total: 11.3s	remaining: 20.8s
353:	learn: 0.3345471	total: 11.4s	remaining: 20.7s
354:	learn: 0.3345407	total: 11.4s	remaining: 20.7s
355:	learn: 0.3345335	total: 11.4s	remaining: 20.7s
356:	learn: 0.3345250	total: 11.5s	remaining: 20.6s
357:	learn: 0.3345222	total: 11.5s	remaining: 20.6s
358:	learn: 0.3345170	total: 11.5s	remaining: 20.6s
359:	learn: 0.3345046	total: 11.6s	remaining: 20.5s
360:	learn: 0.3344925	total: 11.6s	remaining: 20.5s
361:	learn: 0.3344872	total: 11.6s	remaining: 20.5s
362:	learn: 0.3344813	total: 11.7s	remaining: 20.4s
363:	learn: 0.3344706	total: 11.7s	remaining: 20.4s
364:	learn: 0.3344679	total: 11.7s	remaining: 20.4s
365:	learn: 0.3344645	total: 11.7s	remaining: 20.3s
366:	learn: 0.3344597	total: 11.8s	remaining: 20.3s
367:	learn: 0.3344510	total: 11.8s	remaining: 20.3s
368:	learn: 0.3344429	total: 11.8s	remaining: 20.3s
369:	learn: 0.3344327	total: 11.9s	remaining: 20.2s
370:	learn: 0.3344213	total: 11.9s	remaining: 20.2s
371:	learn: 0.3344112	total: 11.9s	remaining: 20.2s
372:	learn: 0.3344050	total: 12s	remaining: 20.1s
373:	learn: 0.3343962	total: 12s	remaining: 20.1s
374:	learn: 0.3343841	total: 12s	remaining: 20.1s
375:	learn: 0.3343718	total: 12.1s	remaining: 20s
376:	learn: 0.3343643	total: 12.1s	remaining: 20s
377:	learn: 0.3343620	total: 12.1s	remaining: 20s
378:	learn: 0.3343610	total: 12.2s	remaining: 19.9s
379:	learn: 0.3343522	total: 12.2s	remaining: 19.9s
380:	learn: 0.3343459	total: 12.2s	remaining: 19.9s
381:	learn: 0.3343431	total: 12.3s	remaining: 19.8s
382:	learn: 0.3343380	total: 12.3s	remaining: 19.8s
383:	learn: 0.3343340	total: 12.3s	remaining: 19.8s
384:	learn: 0.3343242	total: 12.3s	remaining: 19.7s
385:	learn: 0.3343163	total: 12.4s	remaining: 19.7s
386:	learn: 0.3343090	total: 12.4s	remaining: 19.7s
387:	learn: 0.3342995	total: 12.4s	remaining: 19.6s
388:	learn: 0.3342948	total: 12.5s	remaining: 19.6s
389:	learn: 0.3342889	total: 12.5s	remaining: 19.6s
390:	learn: 0.3342813	total: 12.5s	remaining: 19.5s
391:	learn: 0.3342751	total: 12.6s	remaining: 19.5s
392:	learn: 0.3342715	total: 12.6s	remaining: 19.5s
393:	learn: 0.3342648	total: 12.6s	remaining: 19.4s
394:	learn: 0.3342579	total: 12.7s	remaining: 19.4s
395:	learn: 0.3342511	total: 12.7s	remaining: 19.4s
396:	learn: 0.3342437	total: 12.7s	remaining: 19.3s
397:	learn: 0.3342397	total: 12.8s	remaining: 19.3s
398:	learn: 0.3342354	total: 12.8s	remaining: 19.3s
399:	learn: 0.3342318	total: 12.8s	remaining: 19.2s
400:	learn: 0.3342270	total: 12.8s	remaining: 19.2s
401:	learn: 0.3342178	total: 12.9s	remaining: 19.2s
402:	learn: 0.3342149	total: 12.9s	remaining: 19.1s
403:	learn: 0.3342058	total: 12.9s	remaining: 19.1s
404:	learn: 0.3341985	total: 13s	remaining: 19.1s
405:	learn: 0.3341884	total: 13s	remaining: 19s
406:	learn: 0.3341819	total: 13s	remaining: 19s
407:	learn: 0.3341773	total: 13.1s	remaining: 19s
408:	learn: 0.3341649	total: 13.1s	remaining: 18.9s
409:	learn: 0.3341576	total: 13.1s	remaining: 18.9s
410:	learn: 0.3341485	total: 13.2s	remaining: 18.9s
411:	learn: 0.3341393	total: 13.2s	remaining: 18.9s
412:	learn: 0.3341342	total: 13.2s	remaining: 18.8s
413:	learn: 0.3341301	total: 13.3s	remaining: 18.8s
414:	learn: 0.3341242	total: 13.3s	remaining: 18.8s
415:	learn: 0.3341110	total: 13.3s	remaining: 18.7s
416:	learn: 0.3341062	total: 13.4s	remaining: 18.7s
417:	learn: 0.3341016	total: 13.4s	remaining: 18.7s
418:	learn: 0.3340993	total: 13.4s	remaining: 18.6s
419:	learn: 0.3340971	total: 13.5s	remaining: 18.6s
420:	learn: 0.3340891	total: 13.5s	remaining: 18.6s
421:	learn: 0.3340823	total: 13.5s	remaining: 18.5s
422:	learn: 0.3340791	total: 13.6s	remaining: 18.5s
423:	learn: 0.3340735	total: 13.6s	remaining: 18.5s
424:	learn: 0.3340639	total: 13.6s	remaining: 18.4s
425:	learn: 0.3340582	total: 13.7s	remaining: 18.4s
426:	learn: 0.3340538	total: 13.7s	remaining: 18.4s
427:	learn: 0.3340499	total: 13.7s	remaining: 18.3s
428:	learn: 0.3340454	total: 13.8s	remaining: 18.3s
429:	learn: 0.3340403	total: 13.8s	remaining: 18.3s
430:	learn: 0.3340340	total: 13.8s	remaining: 18.2s
431:	learn: 0.3340306	total: 13.8s	remaining: 18.2s
432:	learn: 0.3340257	total: 13.9s	remaining: 18.2s
433:	learn: 0.3340166	total: 13.9s	remaining: 18.1s
434:	learn: 0.3340112	total: 13.9s	remaining: 18.1s
435:	learn: 0.3340092	total: 14s	remaining: 18.1s
436:	learn: 0.3340022	total: 14s	remaining: 18s
437:	learn: 0.3339990	total: 14s	remaining: 18s
438:	learn: 0.3339910	total: 14.1s	remaining: 18s
439:	learn: 0.3339886	total: 14.1s	remaining: 17.9s
440:	learn: 0.3339847	total: 14.1s	remaining: 17.9s
441:	learn: 0.3339773	total: 14.2s	remaining: 17.9s
442:	learn: 0.3339756	total: 14.2s	remaining: 17.8s
443:	learn: 0.3339695	total: 14.2s	remaining: 17.8s
444:	learn: 0.3339615	total: 14.3s	remaining: 17.8s
445:	learn: 0.3339594	total: 14.3s	remaining: 17.8s
446:	learn: 0.3339530	total: 14.3s	remaining: 17.7s
447:	learn: 0.3339476	total: 14.4s	remaining: 17.7s
448:	learn: 0.3339419	total: 14.4s	remaining: 17.7s
449:	learn: 0.3339383	total: 14.4s	remaining: 17.6s
450:	learn: 0.3339293	total: 14.5s	remaining: 17.6s
451:	learn: 0.3339256	total: 14.5s	remaining: 17.6s
452:	learn: 0.3339214	total: 14.5s	remaining: 17.5s
453:	learn: 0.3339184	total: 14.6s	remaining: 17.5s
454:	learn: 0.3339123	total: 14.6s	remaining: 17.5s
455:	learn: 0.3339069	total: 14.6s	remaining: 17.4s
456:	learn: 0.3339029	total: 14.6s	remaining: 17.4s
457:	learn: 0.3338967	total: 14.7s	remaining: 17.4s
458:	learn: 0.3338923	total: 14.7s	remaining: 17.3s
459:	learn: 0.3338860	total: 14.7s	remaining: 17.3s
460:	learn: 0.3338808	total: 14.8s	remaining: 17.3s
461:	learn: 0.3338764	total: 14.8s	remaining: 17.2s
462:	learn: 0.3338701	total: 14.8s	remaining: 17.2s
463:	learn: 0.3338653	total: 14.9s	remaining: 17.2s
464:	learn: 0.3338568	total: 14.9s	remaining: 17.1s
465:	learn: 0.3338518	total: 14.9s	remaining: 17.1s
466:	learn: 0.3338480	total: 15s	remaining: 17.1s
467:	learn: 0.3338453	total: 15s	remaining: 17s
468:	learn: 0.3338379	total: 15s	remaining: 17s
469:	learn: 0.3338323	total: 15.1s	remaining: 17s
470:	learn: 0.3338262	total: 15.1s	remaining: 16.9s
471:	learn: 0.3338222	total: 15.1s	remaining: 16.9s
472:	learn: 0.3338174	total: 15.1s	remaining: 16.9s
473:	learn: 0.3338121	total: 15.2s	remaining: 16.8s
474:	learn: 0.3338070	total: 15.2s	remaining: 16.8s
475:	learn: 0.3338018	total: 15.2s	remaining: 16.8s
476:	learn: 0.3337966	total: 15.3s	remaining: 16.7s
477:	learn: 0.3337902	total: 15.3s	remaining: 16.7s
478:	learn: 0.3337818	total: 15.3s	remaining: 16.7s
479:	learn: 0.3337759	total: 15.4s	remaining: 16.6s
480:	learn: 0.3337665	total: 15.4s	remaining: 16.6s
481:	learn: 0.3337624	total: 15.4s	remaining: 16.6s
482:	learn: 0.3337594	total: 15.5s	remaining: 16.6s
483:	learn: 0.3337558	total: 15.5s	remaining: 16.5s
484:	learn: 0.3337508	total: 15.5s	remaining: 16.5s
485:	learn: 0.3337477	total: 15.6s	remaining: 16.5s
486:	learn: 0.3337460	total: 15.6s	remaining: 16.4s
487:	learn: 0.3337399	total: 15.6s	remaining: 16.4s
488:	learn: 0.3337350	total: 15.6s	remaining: 16.4s

489:	learn: 0.3337311	total: 15.7s	remaining: 16.3s
490:	learn: 0.3337245	total: 15.7s	remaining: 16.3s
491:	learn: 0.3337190	total: 15.7s	remaining: 16.3s
492:	learn: 0.3337147	total: 15.8s	remaining: 16.2s
493:	learn: 0.3337093	total: 15.8s	remaining: 16.2s
494:	learn: 0.3337045	total: 15.8s	remaining: 16.2s
495:	learn: 0.3336971	total: 15.9s	remaining: 16.1s
496:	learn: 0.3336935	total: 15.9s	remaining: 16.1s
497:	learn: 0.3336854	total: 15.9s	remaining: 16.1s
498:	learn: 0.3336793	total: 16s	remaining: 16s
499:	learn: 0.3336760	total: 16s	remaining: 16s
500:	learn: 0.3336735	total: 16s	remaining: 16s
501:	learn: 0.3336656	total: 16.1s	remaining: 15.9s
502:	learn: 0.3336574	total: 16.1s	remaining: 15.9s
503:	learn: 0.3336522	total: 16.1s	remaining: 15.9s
504:	learn: 0.3336451	total: 16.2s	remaining: 15.8s
505:	learn: 0.3336374	total: 16.2s	remaining: 15.8s
506:	learn: 0.3336340	total: 16.2s	remaining: 15.8s
507:	learn: 0.3336310	total: 16.3s	remaining: 15.7s
508:	learn: 0.3336286	total: 16.3s	remaining: 15.7s
509:	learn: 0.3336239	total: 16.3s	remaining: 15.7s
510:	learn: 0.3336171	total: 16.4s	remaining: 15.6s
511:	learn: 0.3336116	total: 16.4s	remaining: 15.6s
512:	learn: 0.3336054	total: 16.4s	remaining: 15.6s
513:	learn: 0.3336027	total: 16.5s	remaining: 15.6s
514:	learn: 0.3336005	total: 16.5s	remaining: 15.5s
515:	learn: 0.3335941	total: 16.5s	remaining: 15.5s
516:	learn: 0.3335881	total: 16.5s	remaining: 15.5s
517:	learn: 0.3335831	total: 16.6s	remaining: 15.4s
518:	learn: 0.3335795	total: 16.6s	remaining: 15.4s
519:	learn: 0.3335718	total: 16.6s	remaining: 15.4s
520:	learn: 0.3335690	total: 16.7s	remaining: 15.3s
521:	learn: 0.3335658	total: 16.7s	remaining: 15.3s
522:	learn: 0.3335613	total: 16.7s	remaining: 15.3s
523:	learn: 0.3335488	total: 16.8s	remaining: 15.2s
524:	learn: 0.3335440	total: 16.8s	remaining: 15.2s
525:	learn: 0.3335404	total: 16.8s	remaining: 15.2s
526:	learn: 0.3335359	total: 16.9s	remaining: 15.1s
527:	learn: 0.3335312	total: 16.9s	remaining: 15.1s
528:	learn: 0.3335272	total: 16.9s	remaining: 15.1s
529:	learn: 0.3335239	total: 17s	remaining: 15s
530:	learn: 0.3335204	total: 17s	remaining: 15s
531:	learn: 0.3335124	total: 17s	remaining: 15s
532:	learn: 0.3335087	total: 17.1s	remaining: 15s
533:	learn: 0.3335018	total: 17.1s	remaining: 14.9s
534:	learn: 0.3334981	total: 17.1s	remaining: 14.9s
535:	learn: 0.3334932	total: 17.2s	remaining: 14.9s
536:	learn: 0.3334846	total: 17.2s	remaining: 14.8s
537:	learn: 0.3334779	total: 17.2s	remaining: 14.8s
538:	learn: 0.3334730	total: 17.2s	remaining: 14.8s
539:	learn: 0.3334662	total: 17.3s	remaining: 14.7s
540:	learn: 0.3334636	total: 17.3s	remaining: 14.7s
541:	learn: 0.3334613	total: 17.3s	remaining: 14.7s
542:	learn: 0.3334568	total: 17.4s	remaining: 14.6s
543:	learn: 0.3334531	total: 17.4s	remaining: 14.6s
544:	learn: 0.3334484	total: 17.4s	remaining: 14.6s
545:	learn: 0.3334435	total: 17.5s	remaining: 14.5s
546:	learn: 0.3334378	total: 17.5s	remaining: 14.5s
547:	learn: 0.3334334	total: 17.5s	remaining: 14.5s
548:	learn: 0.3334305	total: 17.6s	remaining: 14.4s
549:	learn: 0.3334210	total: 17.6s	remaining: 14.4s
550:	learn: 0.3334148	total: 17.6s	remaining: 14.4s
551:	learn: 0.3334091	total: 17.7s	remaining: 14.3s
552:	learn: 0.3334041	total: 17.7s	remaining: 14.3s
553:	learn: 0.3334021	total: 17.7s	remaining: 14.3s
554:	learn: 0.3333982	total: 17.8s	remaining: 14.2s
555:	learn: 0.3333911	total: 17.8s	remaining: 14.2s
556:	learn: 0.3333862	total: 17.8s	remaining: 14.2s
557:	learn: 0.3333797	total: 17.9s	remaining: 14.1s
558:	learn: 0.3333773	total: 17.9s	remaining: 14.1s
559:	learn: 0.3333708	total: 17.9s	remaining: 14.1s
560:	learn: 0.3333672	total: 18s	remaining: 14.1s
561:	learn: 0.3333616	total: 18s	remaining: 14s
562:	learn: 0.3333576	total: 18s	remaining: 14s
563:	learn: 0.3333544	total: 18.1s	remaining: 14s
564:	learn: 0.3333498	total: 18.1s	remaining: 13.9s
565:	learn: 0.3333422	total: 18.1s	remaining: 13.9s
566:	learn: 0.3333373	total: 18.2s	remaining: 13.9s
567:	learn: 0.3333323	total: 18.2s	remaining: 13.8s
568:	learn: 0.3333285	total: 18.2s	remaining: 13.8s
569:	learn: 0.3333226	total: 18.2s	remaining: 13.8s
570:	learn: 0.3333201	total: 18.3s	remaining: 13.7s
571:	learn: 0.3333152	total: 18.3s	remaining: 13.7s
572:	learn: 0.3333127	total: 18.4s	remaining: 13.7s
573:	learn: 0.3333074	total: 18.4s	remaining: 13.6s
574:	learn: 0.3333010	total: 18.4s	remaining: 13.6s
575:	learn: 0.3332977	total: 18.5s	remaining: 13.6s
576:	learn: 0.3332956	total: 18.5s	remaining: 13.6s
577:	learn: 0.3332893	total: 18.5s	remaining: 13.5s
578:	learn: 0.3332855	total: 18.6s	remaining: 13.5s
579:	learn: 0.3332808	total: 18.6s	remaining: 13.5s
580:	learn: 0.3332768	total: 18.6s	remaining: 13.4s
581:	learn: 0.3332713	total: 18.7s	remaining: 13.4s
582:	learn: 0.3332691	total: 18.7s	remaining: 13.4s
583:	learn: 0.3332660	total: 18.7s	remaining: 13.4s
584:	learn: 0.3332629	total: 18.8s	remaining: 13.3s
585:	learn: 0.3332577	total: 18.8s	remaining: 13.3s
586:	learn: 0.3332541	total: 18.8s	remaining: 13.3s
587:	learn: 0.3332488	total: 18.9s	remaining: 13.2s
588:	learn: 0.3332416	total: 18.9s	remaining: 13.2s
589:	learn: 0.3332378	total: 18.9s	remaining: 13.2s
590:	learn: 0.3332316	total: 19s	remaining: 13.1s
591:	learn: 0.3332240	total: 19s	remaining: 13.1s
592:	learn: 0.3332207	total: 19s	remaining: 13.1s
593:	learn: 0.3332158	total: 19.1s	remaining: 13s
594:	learn: 0.3332128	total: 19.1s	remaining: 13s
595:	learn: 0.3332070	total: 19.1s	remaining: 13s
596:	learn: 0.3332020	total: 19.2s	remaining: 12.9s
597:	learn: 0.3331933	total: 19.2s	remaining: 12.9s
598:	learn: 0.3331899	total: 19.3s	remaining: 12.9s
599:	learn: 0.3331873	total: 19.3s	remaining: 12.9s
600:	learn: 0.3331853	total: 19.3s	remaining: 12.8s
601:	learn: 0.3331828	total: 19.4s	remaining: 12.8s
602:	learn: 0.3331755	total: 19.4s	remaining: 12.8s
603:	learn: 0.3331700	total: 19.4s	remaining: 12.7s
604:	learn: 0.3331649	total: 19.5s	remaining: 12.7s
605:	learn: 0.3331598	total: 19.5s	remaining: 12.7s
606:	learn: 0.3331546	total: 19.5s	remaining: 12.6s
607:	learn: 0.3331480	total: 19.6s	remaining: 12.6s
608:	learn: 0.3331435	total: 19.6s	remaining: 12.6s
609:	learn: 0.3331389	total: 19.6s	remaining: 12.5s
610:	learn: 0.3331364	total: 19.7s	remaining: 12.5s
611:	learn: 0.3331304	total: 19.7s	remaining: 12.5s
612:	learn: 0.3331264	total: 19.7s	remaining: 12.4s
613:	learn: 0.3331171	total: 19.7s	remaining: 12.4s
614:	learn: 0.3331155	total: 19.8s	remaining: 12.4s
615:	learn: 0.3331096	total: 19.8s	remaining: 12.4s
616:	learn: 0.3331032	total: 19.8s	remaining: 12.3s
617:	learn: 0.3330987	total: 19.9s	remaining: 12.3s
618:	learn: 0.3330935	total: 19.9s	remaining: 12.3s
619:	learn: 0.3330879	total: 20s	remaining: 12.2s
620:	learn: 0.3330806	total: 20s	remaining: 12.2s
621:	learn: 0.3330742	total: 20s	remaining: 12.2s
622:	learn: 0.3330694	total: 20.1s	remaining: 12.1s
623:	learn: 0.3330637	total: 20.1s	remaining: 12.1s
624:	learn: 0.3330591	total: 20.1s	remaining: 12.1s
625:	learn: 0.3330542	total: 20.2s	remaining: 12.1s
626:	learn: 0.3330514	total: 20.2s	remaining: 12s
627:	learn: 0.3330452	total: 20.3s	remaining: 12s
628:	learn: 0.3330390	total: 20.3s	remaining: 12s
629:	learn: 0.3330334	total: 20.3s	remaining: 11.9s
630:	learn: 0.3330291	total: 20.4s	remaining: 11.9s
631:	learn: 0.3330253	total: 20.4s	remaining: 11.9s
632:	learn: 0.3330191	total: 20.4s	remaining: 11.8s
633:	learn: 0.3330145	total: 20.5s	remaining: 11.8s
634:	learn: 0.3330113	total: 20.5s	remaining: 11.8s
635:	learn: 0.3330071	total: 20.5s	remaining: 11.8s
636:	learn: 0.3330025	total: 20.6s	remaining: 11.7s
637:	learn: 0.3329987	total: 20.6s	remaining: 11.7s
638:	learn: 0.3329954	total: 20.6s	remaining: 11.7s
639:	learn: 0.3329933	total: 20.7s	remaining: 11.6s
640:	learn: 0.3329853	total: 20.7s	remaining: 11.6s
641:	learn: 0.3329784	total: 20.7s	remaining: 11.6s
642:	learn: 0.3329739	total: 20.8s	remaining: 11.5s
643:	learn: 0.3329676	total: 20.8s	remaining: 11.5s
644:	learn: 0.3329610	total: 20.8s	remaining: 11.5s
645:	learn: 0.3329585	total: 20.9s	remaining: 11.4s
646:	learn: 0.3329524	total: 20.9s	remaining: 11.4s
647:	learn: 0.3329489	total: 20.9s	remaining: 11.4s
648:	learn: 0.3329450	total: 20.9s	remaining: 11.3s
649:	learn: 0.3329405	total: 21s	remaining: 11.3s
650:	learn: 0.3329345	total: 21s	remaining: 11.3s
651:	learn: 0.3329315	total: 21s	remaining: 11.2s
652:	learn: 0.3329264	total: 21.1s	remaining: 11.2s
653:	learn: 0.3329192	total: 21.1s	remaining: 11.2s

654:	learn: 0.3329133	total: 21.1s	remaining: 11.1s
655:	learn: 0.3329084	total: 21.2s	remaining: 11.1s
656:	learn: 0.3329035	total: 21.2s	remaining: 11.1s
657:	learn: 0.3328977	total: 21.2s	remaining: 11s
658:	learn: 0.3328931	total: 21.3s	remaining: 11s
659:	learn: 0.3328890	total: 21.3s	remaining: 11s
660:	learn: 0.3328858	total: 21.3s	remaining: 10.9s
661:	learn: 0.3328826	total: 21.4s	remaining: 10.9s
662:	learn: 0.3328786	total: 21.4s	remaining: 10.9s
663:	learn: 0.3328695	total: 21.4s	remaining: 10.8s
664:	learn: 0.3328668	total: 21.5s	remaining: 10.8s
665:	learn: 0.3328642	total: 21.5s	remaining: 10.8s
666:	learn: 0.3328576	total: 21.5s	remaining: 10.7s
667:	learn: 0.3328552	total: 21.6s	remaining: 10.7s
668:	learn: 0.3328507	total: 21.6s	remaining: 10.7s
669:	learn: 0.3328449	total: 21.6s	remaining: 10.6s
670:	learn: 0.3328417	total: 21.7s	remaining: 10.6s
671:	learn: 0.3328382	total: 21.7s	remaining: 10.6s
672:	learn: 0.3328317	total: 21.7s	remaining: 10.6s
673:	learn: 0.3328281	total: 21.7s	remaining: 10.5s
674:	learn: 0.3328228	total: 21.8s	remaining: 10.5s
675:	learn: 0.3328191	total: 21.8s	remaining: 10.5s
676:	learn: 0.3328147	total: 21.8s	remaining: 10.4s
677:	learn: 0.3328062	total: 21.9s	remaining: 10.4s
678:	learn: 0.3328016	total: 21.9s	remaining: 10.4s
679:	learn: 0.3327974	total: 21.9s	remaining: 10.3s
680:	learn: 0.3327932	total: 22s	remaining: 10.3s
681:	learn: 0.3327863	total: 22s	remaining: 10.3s
682:	learn: 0.3327821	total: 22s	remaining: 10.2s
683:	learn: 0.3327762	total: 22.1s	remaining: 10.2s
684:	learn: 0.3327678	total: 22.1s	remaining: 10.2s
685:	learn: 0.3327590	total: 22.1s	remaining: 10.1s
686:	learn: 0.3327558	total: 22.2s	remaining: 10.1s
687:	learn: 0.3327507	total: 22.2s	remaining: 10.1s
688:	learn: 0.3327454	total: 22.2s	remaining: 10s
689:	learn: 0.3327420	total: 22.3s	remaining: 10s
690:	learn: 0.3327360	total: 22.3s	remaining: 9.96s
691:	learn: 0.3327303	total: 22.3s	remaining: 9.93s
692:	learn: 0.3327236	total: 22.3s	remaining: 9.9s
693:	learn: 0.3327175	total: 22.4s	remaining: 9.87s
694:	learn: 0.3327134	total: 22.4s	remaining: 9.83s
695:	learn: 0.3327063	total: 22.4s	remaining: 9.8s
696:	learn: 0.3326999	total: 22.5s	remaining: 9.77s
697:	learn: 0.3326961	total: 22.5s	remaining: 9.74s
698:	learn: 0.3326900	total: 22.5s	remaining: 9.71s
699:	learn: 0.3326855	total: 22.6s	remaining: 9.68s
700:	learn: 0.3326827	total: 22.6s	remaining: 9.64s
701:	learn: 0.3326772	total: 22.6s	remaining: 9.61s
702:	learn: 0.3326693	total: 22.7s	remaining: 9.58s
703:	learn: 0.3326631	total: 22.7s	remaining: 9.55s
704:	learn: 0.3326571	total: 22.7s	remaining: 9.52s
705:	learn: 0.3326506	total: 22.8s	remaining: 9.48s
706:	learn: 0.3326468	total: 22.8s	remaining: 9.45s
707:	learn: 0.3326403	total: 22.8s	remaining: 9.42s
708:	learn: 0.3326352	total: 22.9s	remaining: 9.39s
709:	learn: 0.3326306	total: 22.9s	remaining: 9.36s
710:	learn: 0.3326258	total: 23s	remaining: 9.33s
711:	learn: 0.3326194	total: 23s	remaining: 9.3s
712:	learn: 0.3326151	total: 23s	remaining: 9.27s
713:	learn: 0.3326103	total: 23.1s	remaining: 9.24s
714:	learn: 0.3326040	total: 23.1s	remaining: 9.21s
715:	learn: 0.3326006	total: 23.1s	remaining: 9.18s
716:	learn: 0.3325929	total: 23.2s	remaining: 9.14s
717:	learn: 0.3325873	total: 23.2s	remaining: 9.11s
718:	learn: 0.3325784	total: 23.2s	remaining: 9.08s
719:	learn: 0.3325705	total: 23.3s	remaining: 9.05s
720:	learn: 0.3325658	total: 23.3s	remaining: 9.02s
721:	learn: 0.3325605	total: 23.3s	remaining: 8.98s
722:	learn: 0.3325570	total: 23.4s	remaining: 8.95s
723:	learn: 0.3325495	total: 23.4s	remaining: 8.92s
724:	learn: 0.3325432	total: 23.4s	remaining: 8.89s
725:	learn: 0.3325383	total: 23.5s	remaining: 8.85s
726:	learn: 0.3325346	total: 23.5s	remaining: 8.82s
727:	learn: 0.3325283	total: 23.5s	remaining: 8.79s
728:	learn: 0.3325244	total: 23.6s	remaining: 8.76s
729:	learn: 0.3325202	total: 23.6s	remaining: 8.72s
730:	learn: 0.3325161	total: 23.6s	remaining: 8.69s
731:	learn: 0.3325098	total: 23.6s	remaining: 8.66s
732:	learn: 0.3325045	total: 23.7s	remaining: 8.62s
733:	learn: 0.3324985	total: 23.7s	remaining: 8.59s
734:	learn: 0.3324923	total: 23.7s	remaining: 8.56s
735:	learn: 0.3324875	total: 23.8s	remaining: 8.53s
736:	learn: 0.3324806	total: 23.8s	remaining: 8.49s
737:	learn: 0.3324749	total: 23.8s	remaining: 8.46s
738:	learn: 0.3324681	total: 23.9s	remaining: 8.43s
739:	learn: 0.3324640	total: 23.9s	remaining: 8.4s
740:	learn: 0.3324590	total: 23.9s	remaining: 8.37s
741:	learn: 0.3324556	total: 24s	remaining: 8.34s
742:	learn: 0.3324505	total: 24s	remaining: 8.3s
743:	learn: 0.3324444	total: 24s	remaining: 8.27s
744:	learn: 0.3324387	total: 24.1s	remaining: 8.24s
745:	learn: 0.3324299	total: 24.1s	remaining: 8.21s
746:	learn: 0.3324244	total: 24.1s	remaining: 8.17s
747:	learn: 0.3324195	total: 24.2s	remaining: 8.14s
748:	learn: 0.3324140	total: 24.2s	remaining: 8.11s
749:	learn: 0.3324082	total: 24.2s	remaining: 8.08s
750:	learn: 0.3324010	total: 24.3s	remaining: 8.04s
751:	learn: 0.3323967	total: 24.3s	remaining: 8.01s
752:	learn: 0.3323915	total: 24.3s	remaining: 7.98s
753:	learn: 0.3323872	total: 24.4s	remaining: 7.95s
754:	learn: 0.3323804	total: 24.4s	remaining: 7.92s
755:	learn: 0.3323728	total: 24.4s	remaining: 7.88s
756:	learn: 0.3323647	total: 24.5s	remaining: 7.85s
757:	learn: 0.3323605	total: 24.5s	remaining: 7.82s
758:	learn: 0.3323558	total: 24.5s	remaining: 7.79s
759:	learn: 0.3323517	total: 24.6s	remaining: 7.76s
760:	learn: 0.3323480	total: 24.6s	remaining: 7.72s
761:	learn: 0.3323429	total: 24.6s	remaining: 7.69s
762:	learn: 0.3323355	total: 24.7s	remaining: 7.66s
763:	learn: 0.3323310	total: 24.7s	remaining: 7.63s
764:	learn: 0.3323251	total: 24.7s	remaining: 7.59s
765:	learn: 0.3323200	total: 24.8s	remaining: 7.56s
766:	learn: 0.3323171	total: 24.8s	remaining: 7.53s
767:	learn: 0.3323115	total: 24.8s	remaining: 7.5s
768:	learn: 0.3323069	total: 24.9s	remaining: 7.47s
769:	learn: 0.3322999	total: 24.9s	remaining: 7.44s
770:	learn: 0.3322959	total: 24.9s	remaining: 7.4s
771:	learn: 0.3322904	total: 25s	remaining: 7.37s
772:	learn: 0.3322837	total: 25s	remaining: 7.34s
773:	learn: 0.3322778	total: 25s	remaining: 7.31s
774:	learn: 0.3322744	total: 25.1s	remaining: 7.28s
775:	learn: 0.3322717	total: 25.1s	remaining: 7.24s
776:	learn: 0.3322656	total: 25.1s	remaining: 7.21s
777:	learn: 0.3322604	total: 25.2s	remaining: 7.18s
778:	learn: 0.3322571	total: 25.2s	remaining: 7.15s
779:	learn: 0.3322507	total: 25.2s	remaining: 7.11s
780:	learn: 0.3322444	total: 25.3s	remaining: 7.08s
781:	learn: 0.3322412	total: 25.3s	remaining: 7.05s
782:	learn: 0.3322359	total: 25.3s	remaining: 7.02s
783:	learn: 0.3322274	total: 25.4s	remaining: 6.98s
784:	learn: 0.3322208	total: 25.4s	remaining: 6.95s
785:	learn: 0.3322168	total: 25.4s	remaining: 6.92s
786:	learn: 0.3322116	total: 25.5s	remaining: 6.89s
787:	learn: 0.3322075	total: 25.5s	remaining: 6.86s
788:	learn: 0.3322024	total: 25.5s	remaining: 6.83s
789:	learn: 0.3321984	total: 25.6s	remaining: 6.79s
790:	learn: 0.3321923	total: 25.6s	remaining: 6.76s
791:	learn: 0.3321873	total: 25.6s	remaining: 6.73s
792:	learn: 0.3321836	total: 25.6s	remaining: 6.69s
793:	learn: 0.3321779	total: 25.7s	remaining: 6.66s
794:	learn: 0.3321734	total: 25.7s	remaining: 6.63s
795:	learn: 0.3321674	total: 25.7s	remaining: 6.6s
796:	learn: 0.3321629	total: 25.8s	remaining: 6.56s
797:	learn: 0.3321583	total: 25.8s	remaining: 6.53s
798:	learn: 0.3321539	total: 25.8s	remaining: 6.5s
799:	learn: 0.3321486	total: 25.9s	remaining: 6.47s
800:	learn: 0.3321431	total: 25.9s	remaining: 6.43s
801:	learn: 0.3321361	total: 25.9s	remaining: 6.4s
802:	learn: 0.3321312	total: 26s	remaining: 6.37s
803:	learn: 0.3321261	total: 26s	remaining: 6.33s
804:	learn: 0.3321189	total: 26s	remaining: 6.3s
805:	learn: 0.3321132	total: 26.1s	remaining: 6.27s
806:	learn: 0.3321079	total: 26.1s	remaining: 6.24s
807:	learn: 0.3321026	total: 26.1s	remaining: 6.21s
808:	learn: 0.3320972	total: 26.1s	remaining: 6.17s
809:	learn: 0.3320931	total: 26.2s	remaining: 6.14s
810:	learn: 0.3320886	total: 26.2s	remaining: 6.11s
811:	learn: 0.3320837	total: 26.2s	remaining: 6.08s
812:	learn: 0.3320750	total: 26.3s	remaining: 6.04s
813:	learn: 0.3320709	total: 26.3s	remaining: 6.01s

814:	learn: 0.3320640	total: 26.3s	remaining: 5.98s
815:	learn: 0.3320596	total: 26.4s	remaining: 5.95s
816:	learn: 0.3320544	total: 26.4s	remaining: 5.91s
817:	learn: 0.3320498	total: 26.4s	remaining: 5.88s
818:	learn: 0.3320453	total: 26.5s	remaining: 5.85s
819:	learn: 0.3320412	total: 26.5s	remaining: 5.82s
820:	learn: 0.3320368	total: 26.5s	remaining: 5.78s
821:	learn: 0.3320328	total: 26.6s	remaining: 5.75s
822:	learn: 0.3320293	total: 26.6s	remaining: 5.72s
823:	learn: 0.3320245	total: 26.6s	remaining: 5.68s
824:	learn: 0.3320192	total: 26.7s	remaining: 5.65s
825:	learn: 0.3320121	total: 26.7s	remaining: 5.62s
826:	learn: 0.3320050	total: 26.7s	remaining: 5.59s
827:	learn: 0.3320000	total: 26.7s	remaining: 5.55s
828:	learn: 0.3319960	total: 26.8s	remaining: 5.52s
829:	learn: 0.3319901	total: 26.8s	remaining: 5.49s
830:	learn: 0.3319847	total: 26.8s	remaining: 5.46s
831:	learn: 0.3319768	total: 26.9s	remaining: 5.43s
832:	learn: 0.3319726	total: 26.9s	remaining: 5.39s
833:	learn: 0.3319699	total: 26.9s	remaining: 5.36s
834:	learn: 0.3319644	total: 27s	remaining: 5.33s
835:	learn: 0.3319599	total: 27s	remaining: 5.29s
836:	learn: 0.3319558	total: 27s	remaining: 5.26s
837:	learn: 0.3319526	total: 27.1s	remaining: 5.23s
838:	learn: 0.3319484	total: 27.1s	remaining: 5.2s
839:	learn: 0.3319427	total: 27.1s	remaining: 5.16s
840:	learn: 0.3319356	total: 27.1s	remaining: 5.13s
841:	learn: 0.3319309	total: 27.2s	remaining: 5.1s
842:	learn: 0.3319245	total: 27.2s	remaining: 5.07s
843:	learn: 0.3319211	total: 27.2s	remaining: 5.03s
844:	learn: 0.3319172	total: 27.3s	remaining: 5s
845:	learn: 0.3319118	total: 27.3s	remaining: 4.97s
846:	learn: 0.3319087	total: 27.3s	remaining: 4.94s
847:	learn: 0.3319020	total: 27.4s	remaining: 4.9s
848:	learn: 0.3318976	total: 27.4s	remaining: 4.87s
849:	learn: 0.3318937	total: 27.4s	remaining: 4.84s
850:	learn: 0.3318872	total: 27.5s	remaining: 4.81s
851:	learn: 0.3318824	total: 27.5s	remaining: 4.78s
852:	learn: 0.3318765	total: 27.5s	remaining: 4.74s
853:	learn: 0.3318710	total: 27.6s	remaining: 4.71s
854:	learn: 0.3318652	total: 27.6s	remaining: 4.68s
855:	learn: 0.3318608	total: 27.6s	remaining: 4.65s
856:	learn: 0.3318522	total: 27.7s	remaining: 4.62s
857:	learn: 0.3318460	total: 27.7s	remaining: 4.58s
858:	learn: 0.3318414	total: 27.7s	remaining: 4.55s
859:	learn: 0.3318383	total: 27.8s	remaining: 4.52s
860:	learn: 0.3318340	total: 27.8s	remaining: 4.49s
861:	learn: 0.3318296	total: 27.8s	remaining: 4.45s
862:	learn: 0.3318250	total: 27.9s	remaining: 4.42s
863:	learn: 0.3318211	total: 27.9s	remaining: 4.39s
864:	learn: 0.3318155	total: 27.9s	remaining: 4.36s
865:	learn: 0.3318118	total: 27.9s	remaining: 4.32s
866:	learn: 0.3318089	total: 28s	remaining: 4.29s
867:	learn: 0.3318029	total: 28s	remaining: 4.26s
868:	learn: 0.3317975	total: 28s	remaining: 4.22s
869:	learn: 0.3317912	total: 28.1s	remaining: 4.19s
870:	learn: 0.3317874	total: 28.1s	remaining: 4.16s
871:	learn: 0.3317830	total: 28.1s	remaining: 4.13s
872:	learn: 0.3317786	total: 28.2s	remaining: 4.09s
873:	learn: 0.3317748	total: 28.2s	remaining: 4.06s
874:	learn: 0.3317702	total: 28.2s	remaining: 4.03s
875:	learn: 0.3317674	total: 28.2s	remaining: 4s
876:	learn: 0.3317637	total: 28.3s	remaining: 3.96s
877:	learn: 0.3317597	total: 28.3s	remaining: 3.93s
878:	learn: 0.3317536	total: 28.3s	remaining: 3.9s
879:	learn: 0.3317484	total: 28.4s	remaining: 3.87s
880:	learn: 0.3317441	total: 28.4s	remaining: 3.84s
881:	learn: 0.3317400	total: 28.4s	remaining: 3.8s
882:	learn: 0.3317351	total: 28.5s	remaining: 3.77s
883:	learn: 0.3317311	total: 28.5s	remaining: 3.74s
884:	learn: 0.3317275	total: 28.5s	remaining: 3.71s
885:	learn: 0.3317218	total: 28.6s	remaining: 3.67s
886:	learn: 0.3317154	total: 28.6s	remaining: 3.64s
887:	learn: 0.3317106	total: 28.6s	remaining: 3.61s
888:	learn: 0.3317039	total: 28.7s	remaining: 3.58s
889:	learn: 0.3316964	total: 28.7s	remaining: 3.54s
890:	learn: 0.3316921	total: 28.7s	remaining: 3.51s
891:	learn: 0.3316882	total: 28.7s	remaining: 3.48s
892:	learn: 0.3316823	total: 28.8s	remaining: 3.45s
893:	learn: 0.3316789	total: 28.8s	remaining: 3.42s
894:	learn: 0.3316727	total: 28.8s	remaining: 3.38s
895:	learn: 0.3316675	total: 28.9s	remaining: 3.35s
896:	learn: 0.3316637	total: 28.9s	remaining: 3.32s
897:	learn: 0.3316606	total: 28.9s	remaining: 3.29s
898:	learn: 0.3316576	total: 29s	remaining: 3.25s
899:	learn: 0.3316542	total: 29s	remaining: 3.22s
900:	learn: 0.3316492	total: 29s	remaining: 3.19s
901:	learn: 0.3316448	total: 29.1s	remaining: 3.16s
902:	learn: 0.3316386	total: 29.1s	remaining: 3.12s
903:	learn: 0.3316364	total: 29.1s	remaining: 3.09s
904:	learn: 0.3316320	total: 29.1s	remaining: 3.06s
905:	learn: 0.3316252	total: 29.2s	remaining: 3.03s
906:	learn: 0.3316203	total: 29.2s	remaining: 3s
907:	learn: 0.3316155	total: 29.2s	remaining: 2.96s
908:	learn: 0.3316099	total: 29.3s	remaining: 2.93s
909:	learn: 0.3316038	total: 29.3s	remaining: 2.9s
910:	learn: 0.3316001	total: 29.3s	remaining: 2.87s
911:	learn: 0.3315952	total: 29.4s	remaining: 2.83s
912:	learn: 0.3315914	total: 29.4s	remaining: 2.8s
913:	learn: 0.3315858	total: 29.4s	remaining: 2.77s
914:	learn: 0.3315817	total: 29.5s	remaining: 2.74s
915:	learn: 0.3315752	total: 29.5s	remaining: 2.7s
916:	learn: 0.3315699	total: 29.5s	remaining: 2.67s
917:	learn: 0.3315664	total: 29.6s	remaining: 2.64s
918:	learn: 0.3315591	total: 29.6s	remaining: 2.61s
919:	learn: 0.3315531	total: 29.6s	remaining: 2.58s
920:	learn: 0.3315477	total: 29.7s	remaining: 2.54s
921:	learn: 0.3315416	total: 29.7s	remaining: 2.51s
922:	learn: 0.3315370	total: 29.7s	remaining: 2.48s
923:	learn: 0.3315316	total: 29.8s	remaining: 2.45s
924:	learn: 0.3315267	total: 29.8s	remaining: 2.42s
925:	learn: 0.3315228	total: 29.8s	remaining: 2.38s
926:	learn: 0.3315191	total: 29.9s	remaining: 2.35s
927:	learn: 0.3315144	total: 29.9s	remaining: 2.32s
928:	learn: 0.3315109	total: 29.9s	remaining: 2.29s
929:	learn: 0.3315049	total: 30s	remaining: 2.25s
930:	learn: 0.3314959	total: 30s	remaining: 2.22s
931:	learn: 0.3314917	total: 30s	remaining: 2.19s
932:	learn: 0.3314885	total: 30s	remaining: 2.16s
933:	learn: 0.3314847	total: 30.1s	remaining: 2.13s
934:	learn: 0.3314788	total: 30.1s	remaining: 2.09s
935:	learn: 0.3314735	total: 30.1s	remaining: 2.06s
936:	learn: 0.3314677	total: 30.2s	remaining: 2.03s
937:	learn: 0.3314627	total: 30.2s	remaining: 2s
938:	learn: 0.3314580	total: 30.2s	remaining: 1.96s
939:	learn: 0.3314516	total: 30.3s	remaining: 1.93s
940:	learn: 0.3314458	total: 30.3s	remaining: 1.9s
941:	learn: 0.3314420	total: 30.3s	remaining: 1.87s
942:	learn: 0.3314394	total: 30.4s	remaining: 1.83s
943:	learn: 0.3314341	total: 30.4s	remaining: 1.8s
944:	learn: 0.3314272	total: 30.4s	remaining: 1.77s
945:	learn: 0.3314236	total: 30.4s	remaining: 1.74s
946:	learn: 0.3314204	total: 30.5s	remaining: 1.71s
947:	learn: 0.3314152	total: 30.5s	remaining: 1.67s
948:	learn: 0.3314106	total: 30.5s	remaining: 1.64s
949:	learn: 0.3314066	total: 30.6s	remaining: 1.61s
950:	learn: 0.3314027	total: 30.6s	remaining: 1.58s
951:	learn: 0.3313959	total: 30.6s	remaining: 1.54s
952:	learn: 0.3313913	total: 30.7s	remaining: 1.51s
953:	learn: 0.3313827	total: 30.7s	remaining: 1.48s
954:	learn: 0.3313776	total: 30.7s	remaining: 1.45s
955:	learn: 0.3313748	total: 30.8s	remaining: 1.42s
956:	learn: 0.3313687	total: 30.8s	remaining: 1.38s
957:	learn: 0.3313656	total: 30.8s	remaining: 1.35s
958:	learn: 0.3313613	total: 30.9s	remaining: 1.32s
959:	learn: 0.3313554	total: 30.9s	remaining: 1.29s
960:	learn: 0.3313508	total: 30.9s	remaining: 1.25s
961:	learn: 0.3313486	total: 31s	remaining: 1.22s
962:	learn: 0.3313442	total: 31s	remaining: 1.19s
963:	learn: 0.3313404	total: 31s	remaining: 1.16s
964:	learn: 0.3313356	total: 31s	remaining: 1.13s
965:	learn: 0.3313311	total: 31.1s	remaining: 1.09s
966:	learn: 0.3313266	total: 31.1s	remaining: 1.06s
967:	learn: 0.3313198	total: 31.1s	remaining: 1.03s
968:	learn: 0.3313162	total: 31.2s	remaining: 997ms
969:	learn: 0.3313100	total: 31.2s	remaining: 965ms
970:	learn: 0.3313064	total: 31.2s	remaining: 933ms
971:	learn: 0.3313025	total: 31.3s	remaining: 901ms
972:	learn: 0.3312985	total: 31.3s	remaining: 869ms
973:	learn: 0.3312914	total: 31.3s	remaining: 836ms
974:	learn: 0.3312852	total: 31.4s	remaining: 804ms

975:	learn: 0.3312794	total: 31.4s	remaining: 772ms
976:	learn: 0.3312745	total: 31.4s	remaining: 740ms
977:	learn: 0.3312705	total: 31.5s	remaining: 708ms
978:	learn: 0.3312656	total: 31.5s	remaining: 676ms
979:	learn: 0.3312584	total: 31.5s	remaining: 643ms
980:	learn: 0.3312537	total: 31.6s	remaining: 611ms
981:	learn: 0.3312487	total: 31.6s	remaining: 579ms
982:	learn: 0.3312450	total: 31.6s	remaining: 547ms
983:	learn: 0.3312389	total: 31.7s	remaining: 515ms
984:	learn: 0.3312343	total: 31.7s	remaining: 483ms
985:	learn: 0.3312317	total: 31.7s	remaining: 450ms
986:	learn: 0.3312295	total: 31.8s	remaining: 418ms
987:	learn: 0.3312228	total: 31.8s	remaining: 386ms
988:	learn: 0.3312182	total: 31.8s	remaining: 354ms
989:	learn: 0.3312115	total: 31.8s	remaining: 322ms
990:	learn: 0.3312075	total: 31.9s	remaining: 289ms
991:	learn: 0.3312030	total: 31.9s	remaining: 257ms
992:	learn: 0.3311982	total: 31.9s	remaining: 225ms
993:	learn: 0.3311938	total: 32s	remaining: 193ms
994:	learn: 0.3311884	total: 32s	remaining: 161ms
995:	learn: 0.3311820	total: 32s	remaining: 129ms
996:	learn: 0.3311766	total: 32.1s	remaining: 96.5ms
997:	learn: 0.3311717	total: 32.1s	remaining: 64.3ms
998:	learn: 0.3311679	total: 32.1s	remaining: 32.2ms
999:	learn: 0.3311645	total: 32.2s	remaining: 0us

In [257]:
from sklearn.metrics import accuracy_score
round(accuracy_score(y_test, model.predict(X_test)), 3)

0.894

In [258]:
model.save_model('model', format="cbm")

# Тестируем работу модели при запросе

In [259]:
all_posts['predict'] = model.predict_proba(all_posts.drop('post_id',axis=1))[:, 1]

In [260]:
all_posts

,gender,age,country_Belarus,country_Cyprus,country_Estonia,country_Finland,country_Kazakhstan,country_Latvia,country_Russia,country_Switzerland,...,DistanceTo14thCluster,DistanceTo15thCluster,attraction,topic_covid,topic_entertainment,topic_movie,topic_politics,topic_sport,topic_tech,predict
0,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.274009,3.226359,1,0,0,0,0,0,0,0.098942
1,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.260491,3.178570,0,0,0,0,0,0,0,0.082608
2,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.399966,3.126604,1,0,0,0,0,0,0,0.093992
3,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,3.584817,3.369332,1,0,0,0,0,0,0,0.084381
4,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,2.591954,2.823423,1,0,0,0,0,0,0,0.087795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.416083,2.974245,1,0,0,1,0,0,0,0.122910
7019,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.003729,2.832663,1,0,0,1,0,0,0,0.119446
7020,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.761077,2.676703,0,0,0,1,0,0,0,0.112879
7021,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.028654,3.388523,0,0,0,1,0,0,0,0.143404
7022,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.672995,3.047235,1,0,0,1,0,0,0,0.126755

In [261]:
tuple(all_posts.sort_values('predict', ascending=False)['post_id'].head(5))

(5646, 7171, 7172, 5530, 5112)

# Загружаем модель

In [262]:
import os

def get_model_path(path: str) -> str:
    if os.environ.get("IS_LMS") == "1":  # проверяем где выполняется код в лмс, или локально. Немного магии
        MODEL_PATH = '/workdir/user_input/model'
    else:
        MODEL_PATH = path
    return MODEL_PATH

def load_models():
    model_path = get_model_path("/my/super/path")
    
    model = CatBoostClassifier() 
    
    model.load_model(model_path)
    
    return model

In [218]:
post_test.head(2)

,post_id,text,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,...,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction,topic_covid,topic_entertainment,topic_movie,topic_politics,topic_sport,topic_tech
0,1,UK economy facing major risks\n\nThe UK manufa...,8,3.317282,3.626825,3.504385,2.107590,2.673781,3.362377,1.969380,...,3.299252,3.274009,3.226359,1,0,0,0,0,0,0
1,2,Aids and climate top Davos agenda\n\nClimate c...,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098747,1.947727,...,2.774500,3.260491,3.178570,0,0,0,0,0,0,0

# Выгрузка признаков

In [219]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
    "postgres.lab.karpov.courses:6432/startml"
)

df_post_to_sql = post_test

df_post_to_sql.to_sql('tkachenko_a_post_mod_features__lesson_22', if_exists='replace', con=engine, index=False) # записываем таблицу

#df = test
#df_user_to_sql = df_user
#df_post_to_sql = df_post

#df.to_sql('tkachenko_a_features_lesson_22', if_exists='replace', con=engine, index=False) # записываем таблицу
#df_user_to_sql.to_sql('tkachenko_a_user_features__lesson_22', if_exists='replace', con=engine, index=False) # записываем таблицу
#df_post_to_sql.to_sql('tkachenko_a_post_features__lesson_22', if_exists='replace', con=engine, index=False) # записываем таблицу

df = pd.read_sql('SELECT * FROM tkachenko_a_post_mod_features__lesson_22', con=engine) # считываем таблицу

In [220]:
pd.read_sql('SELECT * FROM tkachenko_a_post_mod_features__lesson_22', con=engine) # считываем таблицу

,post_id,text,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,...,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,attraction,topic_covid,topic_entertainment,topic_movie,topic_politics,topic_sport,topic_tech
0,1,UK economy facing major risks\n\nThe UK manufa...,8,3.317282,3.626825,3.504386,2.107590,2.673781,3.362377,1.969380,...,3.299252,3.274009,3.226359,1,0,0,0,0,0,0
1,2,Aids and climate top Davos agenda\n\nClimate c...,8,3.175854,3.332851,3.201369,2.080955,2.344407,3.098746,1.947727,...,2.774500,3.260491,3.178570,0,0,0,0,0,0,0
2,3,Asian quake hits European shares\n\nShares in ...,8,3.206180,3.420908,3.228868,2.183235,2.723450,3.286630,2.831849,...,2.775532,3.399967,3.126604,1,0,0,0,0,0,0
3,4,India power shares jump on debut\n\nShares in ...,8,3.616450,2.843541,3.649253,2.582405,3.227174,3.933870,3.203395,...,3.559877,3.584817,3.369332,1,0,0,0,0,0,0
4,5,Lacroix label bought by US firm\n\nLuxury good...,8,2.602314,3.101309,2.821453,1.537728,1.803597,3.012253,2.673844,...,2.418449,2.591953,2.823423,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7314,Although the likeliness of someone focusing on...,0,1.179555,2.352704,2.846943,2.361339,2.511536,3.481241,3.138551,...,3.259588,1.718896,3.117846,1,0,0,1,0,0,0
7019,7315,"OK, I would not normally watch a Farrelly brot...",0,0.879528,2.180947,2.797818,2.564929,2.130065,3.268162,3.195646,...,2.829822,1.416082,2.974245,1,0,0,1,0,0,0
7020,7316,I give this movie 2 stars purely because of it...,0,0.698967,2.086715,2.490488,2.322584,2.111093,3.286735,3.083744,...,3.111119,1.003729,2.832663,1,0,0,1,0,0,0
7021,7317,I cant believe this film was allowed to be mad...,0,1.161841,2.444997,2.193800,2.647159,2.271674,3.361959,3.267647,...,3.014389,1.761077,2.676703,0,0,0,1,0,0,0
7022,7319,Piece of subtle art. Maybe a masterpiece. Doub...,7,1.778338,2.169969,2.766120,2.585927,2.400287,3.402753,3.306942,...,3.004033,1.672995,3.047235,1,0,0,1,0,0,0

In [221]:
import pandas as pd
from sqlalchemy import create_engine


def batch_load_sql(query: str) -> pd.DataFrame:
    CHUNKSIZE = 200000
    engine = create_engine(
        "postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
    )
    conn = engine.connect().execution_options(stream_results=True)
    chunks = []
    for chunk_dataframe in pd.read_sql(query, conn, chunksize=CHUNKSIZE):
        chunks.append(chunk_dataframe)
    conn.close()
    return pd.concat(chunks, ignore_index=True)

def load_features() -> pd.DataFrame:
    result = batch_load_sql('SELECT * FROM tkachenko_a_features_lesson_22')
    
    return result